import {
  Activity,
  AlertTriangle,
  ArrowLeftRight,
  Award,
  BadgeDollarSign,
  Ban,
  BarChart3,
  Bell,
  BellRing,
  Blocks,
  BookA,
  BookCheck,
  BookOpen,
  BookUser,
  Bot,
  Briefcase,
  Building,
  Calculator,
  Calendar,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  ChartArea,
  ChartBar,
  CheckSquare,
  CircleHelp,
  CircleUser,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Coins,
  Columns3,
  Compass,
  Contact,
  CreditCard,
  Crosshair,
  Crown,
  DatabaseZap,
  DoorOpen,
  FileCheck,
  FileInput,
  FilePen,
  FileSearch,
  FileText,
  Files,
  Filter,
  Flag,
  FlagTriangleRight,
  FlaskConical,
  FolderKanban,
  FolderOpen,
  Forward,
  Gamepad2,
  Gauge,
  GitCompare,
  GraduationCap,
  Handshake,
  Headset,
  Heart,
  HeartHandshake,
  HeartPulse,
  History,
  Import,
  Inbox,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutTemplate,
  Library,
  LifeBuoy,
  LineChart,
  List,
  ListChecks,
  ListFilter,
  ListOrdered,
  ListTodo,
  LogOut,
  Mail,
  MailPlus,
  Map,
  MapPinned,
  Megaphone,
  MessageCircle,
  MessageCircleMore,
  MessageSquare,
  MessagesSquare,
  Mic,
  Network,
  Newspaper,
  NotebookPen,
  NotebookText,
  PanelsTopLeft,
  PartyPopper,
  PhoneCall,
  PhoneOutgoing,
  PieChart,
  Plug,
  Presentation,
  Projector,
  Quote,
  RefreshCw,
  Rocket,
  Route,
  Scale,
  ScanLine,
  School,
  ScrollText,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Signature,
  Signpost,
  Siren,
  SlidersHorizontal,
  Sparkles,
  Sprout,
  SquareKanban,
  Store,
  Tag,
  Tags,
  Target,
  TextCursorInput,
  Ticket,
  Timer,
  ToggleRight,
  TreeDeciduous,
  TrendingUp,
  Trophy,
  Upload,
  UserCheck,
  UserCog,
  UserSearch,
  Users,
  UsersRound,
  Video,
  Wallet,
  Waypoints,
  Zap,
  Globe,
  Telescope,
  FolderInput,
  Rows3,
  BadgeCheck,
  KeyRound,
  ChartNoAxesColumn,
  type LucideIcon,
} from "lucide-react";

// One icon per nav destination. Keyed by href so both the top-level category and
// any child leaf resolve their own glyph. Every top-level category across the
// founder, investor, and admin workspaces is mapped here — anything unmapped
// falls back to Flag (see getWorkspaceNavIcon). nav-icons.test.ts fails if two pages in
// one workspace menu share an icon, so map every new menu page here.
export const workspaceNavIconByHref: Record<string, LucideIcon> = {
  // ── Founder ───────────────────────────────────────────────────────────────
  "/founder": LayoutDashboard,
  "/founder/dashboard": LayoutDashboard,
  "/founder/onboarding": Rocket, // Stage 1 – Onboarding
  "/founder/readiness": ClipboardCheck, // Stage 2 – Preparation (also "Readiness checklist")
  // ── Stage 2 – Preparation children (distinct icon each) ───────────────────
  "/founder/stages/preparation": Map,
  "/founder/readiness/wizard": Gauge, // Capital Readiness Rating
  "/founder/readiness/data-room": FolderOpen,
  "/founder/preview": FileText, // One pager
  "/founder/business-plan": BookOpen,
  "/founder/pitch-deck": Presentation,
  "/founder/pitch-deck-analyzer": ScanLine,
  "/founder/market-claim": Crosshair,
  "/founder/financial-model": Calculator,
  "/founder/cap-table": PieChart,
  "/founder/valuation": Scale,
  "/founder/report": FileSearch, // AI diligence report
  "/founder/pitch-practice": Mic, // Prep & practice
  "/founder/investors": Target, // Stage 3 – Marketing
  "/founder/deal-room": FlagTriangleRight, // Stage 4 – Closing
  "/founder/readiness/diligence": ShieldCheck,
  "/founder/readiness/documents": FileCheck,
  "/founder/readiness/missing": AlertTriangle,
  "/founder/documents": Files,
  "/founder/private-market": Store,
  "/founder/inbox": MessageSquare, // Communications
  "/founder/messages": MessagesSquare,
  "/founder/updates": Mail,
  "/founder/calendar": Calendar,
  "/founder/schedule": CalendarClock,
  "/founder/events": PartyPopper,
  "/founder/tasks": CheckSquare,
  "/founder/help": Compass,
  "/founder/support": LifeBuoy,
  "/founder/reg-cf": Sparkles,
  "/founder/investors/outreach": MessageSquare,
  "/founder/investors/matches": Sparkles,
  "/founder/matches": Sparkles,
  "/founder/contacts": BookUser,
  "/founder/matching": GitCompare,
  "/founder/capital-raise": TrendingUp,
  "/founder/learning": GraduationCap,
  "/founder/analytics": LineChart,
  "/founder/journey": ListChecks,
  "/founder/actions": ListTodo,
  "/founder/settings": Settings,

  // ── Every founder menu page has its own icon (no repeats in one menu) ─────
  "/founder/stages/onboarding": Signpost,
  "/founder/stages/marketing": MapPinned,
  "/founder/stages/closing": Route,
  "/founder/deploy": Megaphone, // Outreach
  "/founder/investor-pipeline": SquareKanban, // Investor CRM
  "/founder/events/present": Projector, // Present at event
  "/founder/offering-type": Tag,
  "/founder/spvs": Wallet,
  "/founder/investor-update": Newspaper,
  "/founder/milestones": Trophy,
  "/founder/outreach-report": ClipboardList,
  "/founder/board-prep": Briefcase,
  "/founder/term-sheet": ScrollText,
  "/founder/kpi-glossary": BookA,
  "/founder/learning/courses": Library,
  "/founder/learning/plan": NotebookPen,
  "/founder/learning/schedule": CalendarDays,
  "/founder/learning/progress": Activity,
  "/founder/learning/stages/stage_0": Blocks,
  "/founder/learning/stages/stage_1": Sprout,
  "/founder/learning/stages/stage_2": TreeDeciduous,
  "/founder/learning/stages/stage_3": LogOut,
  "/founder/settings/team": UsersRound,
  "/founder/settings/billing": CreditCard,
  "/founder/settings/integrations": Plug,
  "/founder/settings/feedback": MessageCircle,

  // ── Investor ─────────────────────────────────────────────────────────────
  "/investor/dashboard": LayoutDashboard,
  "/investor/onboarding": CircleUser, // Profile
  "/investor/verification": ShieldCheck, // Identity & accreditation
  "/investor/opportunities": Store, // Private Market
  "/investor/matches": Sparkles,
  "/investor/matching": GitCompare,
  "/investor/partner-score": Award,
  "/investor/watchlist": Heart,
  "/investor/interest-pipeline": TrendingUp,
  "/investor/deal-room": Handshake,
  "/investor/deals": FileCheck,
  "/investor/portfolio": PieChart,
  "/investor/spvs": Wallet,
  "/investor/activity": Activity,
  "/investor/actions": ListChecks,
  "/investor/tasks": CheckSquare,
  "/investor/inbox": MessageSquare, // Communications
  "/investor/messages": MessagesSquare,
  "/investor/calendar": Calendar,
  "/investor/schedule": CalendarClock,
  "/investor/learning": School,
  "/investor/analytics": LineChart,
  "/investor/settings": Settings,

  // Shared
  "/credits": Coins,
  "/notifications": Bell,
  "/events": PartyPopper,

  // ── Admin ────────────────────────────────────────────────────────────────
  "/admin": LayoutDashboard,
  "/admin/dashboard": LayoutDashboard,
  "/admin/contacts": Contact,
  "/admin/sales/contacts": Users,
  "/admin/ceo": Crown,
  "/admin/ir-funnel": Filter,
  "/admin/sales": ShoppingCart,
  "/admin/companies": Building,
  "/admin/investors": Users,
  "/admin/support": Headset,
  "/admin/founders-stuck": AlertTriangle,
  "/admin/prospect-intros": ArrowLeftRight,
  "/admin/playbook": HeartHandshake, // Investor Relations
  "/admin/crm": MessageSquare, // Investor Relations CRM
  "/admin/crm/pipeline": TrendingUp,
  "/admin/crm/messages": MessagesSquare,
  "/admin/crm/outreach": Rocket,
  "/admin/crm/unclassified": CircleHelp,
  "/admin/crm/connectors": RefreshCw,
  "/admin/intro-requests": Forward,
  "/admin/marketplace": Store,
  "/admin/deal-rooms": DoorOpen,
  "/admin/spvs": Wallet,
  "/admin/matching": GitCompare,
  "/admin/matching/prospects": UserSearch,
  "/admin/outreach-qualification": ListFilter,
  "/admin/partner-scores": Award,
  "/admin/marketing": Megaphone, // Marketing
  "/admin/events": PartyPopper, // Events
  "/admin/events/email": Mail,
  "/admin/events/brochure": FileText,
  "/admin/voice": Mic, // Voice
  "/admin/investor-directory": Telescope,
  "/admin/investor-directory/records": Rows3,
  "/admin/investor-directory/imports": FolderInput,
  "/admin/investor-directory/verification": BadgeCheck,
  "/admin/investor-directory/access": KeyRound,
  "/admin/investor-directory/usage": ChartNoAxesColumn,
  "/founder/investor-directory": Globe,
  "/admin/actions": ListTodo,
  "/admin/tasks": CheckSquare,
  "/admin/portfolio": PieChart,
  "/admin/readiness": Gauge,
  "/admin/data-room": ClipboardCheck,
  "/admin/learning": GraduationCap,
  "/admin/manual": BookOpen,
  "/admin/analytics": LineChart,
  "/admin/compliance": Shield,
  "/admin/diligence": FileCheck,
  "/admin/audit": ScrollText,
  "/admin/meetings": CalendarClock,
  "/admin/inbox": Inbox,
  "/admin/calendar": Calendar,
  "/admin/meet": Video,
  "/admin/signatures": Signature,
  "/admin/users/manage": UsersRound,
  "/admin/users/permissions": ShieldCheck,
  "/admin/feature-controls": ToggleRight,
  "/admin/billing": CreditCard,
  "/admin/accounts": Landmark,
  "/admin/profile": UserCog,
  "/admin/integrations": Settings, // System
  "/admin/queues": Layers,
  "/admin/automation": Zap,
  "/admin/reports": BarChart3,
  "/admin/imports": Upload,
  "/admin/insights": Sparkles,
  "/admin/system-health": HeartPulse,
  "/admin/beta-operations": FlaskConical,
  "/admin/page-builder-lab": PanelsTopLeft,
  "/admin/funnels": Waypoints,

  // ── Every admin menu page has its own icon (no repeats in one menu) ───────
  "/admin/sales/opportunities": Target,
  "/admin/sales/pipeline": Columns3,
  "/admin/sales/contracts": FilePen,
  "/admin/sales/settings": SlidersHorizontal,
  "/admin/marketing/plan": NotebookPen,
  "/admin/marketing/contacts": BookUser,
  "/admin/marketing/lists": List,
  "/admin/marketing/campaigns": Send,
  "/admin/marketing/sequences": ListOrdered,
  "/admin/marketing/templates": LayoutTemplate,
  "/admin/marketing/testimonials": Quote,
  "/admin/marketing/analytics": ChartBar,
  "/admin/marketing/aeo": Bot,
  "/admin/marketing/suppressions": Ban,
  "/admin/marketing/settings/notifications": BellRing,
  "/admin/ir": HeartHandshake, // Investor Relations
  "/admin/ir/projects": FolderKanban,
  "/admin/ir/tasks": ClipboardList,
  "/admin/ir/import": Import,
  "/admin/social": Share2,
  "/admin/events/applications": FileInput,
  "/admin/events/sponsors": BadgeDollarSign,
  "/admin/events/invitations": MailPlus,
  "/admin/events/registrations": Ticket,
  "/admin/events/networking": Network,
  "/admin/events/analytics": ChartArea,
  "/admin/events/gamification": Gamepad2,
  "/admin/voice/campaigns": PhoneOutgoing,
  "/admin/voice/calls": PhoneCall,
  "/admin/voice/consent-ledger": BookCheck,
  "/admin/voice/performance": Timer,
  "/admin/schedule": CalendarRange,
  "/admin/activity": History,
  "/admin/activity/alerts": Siren,
  "/admin/activity/assignments": UserCheck,
  "/admin/fit": Crosshair,
  "/admin/investors/enrich": DatabaseZap,
  "/admin/message-activity": MessageCircleMore,
  "/admin/support/log": NotebookText,
  "/admin/learning/courses": Library,
  "/admin/learning/founders": School,
  "/admin/pricing": Tags,
  "/admin/profile-fields": TextCursorInput,
  "/admin/scheduled-jobs": Clock,
};

export function getWorkspaceNavIcon(href: string): LucideIcon {
  return workspaceNavIconByHref[href] ?? Flag;
}
