import {
  Activity,
  BarChart3,
  BookOpen,
  Building2,
  CreditCard,
  FileText,
  Flag,
  GraduationCap,
  Heart,
  LayoutDashboard,
  LineChart,
  ListTodo,
  MessageSquare,
  Rocket,
  Settings,
  Shield,
  ShieldCheck,
  ScrollText,
  Sparkles,
  Zap,
  Target,
  TrendingUp,
  Users,
  Upload,
  Wallet,
  type LucideIcon,
} from "lucide-react";

export const workspaceNavIconByHref: Record<string, LucideIcon> = {
  "/founder/dashboard": LayoutDashboard,
  "/founder/readiness": Target,
  "/founder/documents": FileText,
  "/founder/investors": Users,
  "/founder/messages": MessageSquare,
  "/founder/capital-raise": Rocket,
  "/founder/learning": GraduationCap,
  "/founder/analytics": LineChart,
  "/founder/settings": Settings,
  "/investor/dashboard": LayoutDashboard,
  "/investor/onboarding": Sparkles,
  "/investor/opportunities": Building2,
  "/investor/watchlist": Heart,
  "/investor/interest-pipeline": TrendingUp,
  "/investor/spvs": Wallet,
  "/investor/portfolio": BarChart3,
  "/investor/messages": MessageSquare,
  "/investor/analytics": Activity,
  "/investor/settings": Settings,
  "/admin/dashboard": LayoutDashboard,
  "/admin/companies": Building2,
  "/admin/spvs": Wallet,
  "/admin/investors": Users,
  "/admin/learning": GraduationCap,
  "/admin/crm": MessageSquare,
  "/admin/billing": CreditCard,
  "/admin/diligence": FileText,
  "/admin/compliance": Shield,
  "/admin/audit": ScrollText,
  "/admin/queues": ListTodo,
  "/admin/automation": Zap,
  "/admin/reports": BarChart3,
  "/admin/imports": Upload,
  "/admin/analytics": LineChart,
  "/admin/insights": Sparkles,
  "/admin/system-health": Activity,
  "/admin/page-builder-lab": LayoutDashboard,
  "/admin/users/permissions": ShieldCheck,
};

export function getWorkspaceNavIcon(href: string): LucideIcon {
  return workspaceNavIconByHref[href] ?? Flag;
}
