import {
  Activity,
  AlertTriangle,
  ArrowLeftRight,
  Award,
  BarChart3,
  Bell,
  BookOpen,
  Building,
  CalendarClock,
  Calendar,
  Calculator,
  CheckSquare,
  CircleUser,
  ClipboardCheck,
  Coins,
  Compass,
  CreditCard,
  Crosshair,
  Crown,
  DoorOpen,
  FileCheck,
  FileSearch,
  FileText,
  Files,
  Filter,
  FolderOpen,
  Flag,
  FlagTriangleRight,
  Forward,
  Gauge,
  GraduationCap,
  Handshake,
  Headset,
  Heart,
  HeartHandshake,
  Inbox,
  Landmark,
  LayoutDashboard,
  LifeBuoy,
  LineChart,
  ListChecks,
  ListTodo,
  Mail,
  Map,
  Megaphone,
  MessageSquare,
  Mic,
  PartyPopper,
  PieChart,
  Presentation,
  Rocket,
  Scale,
  ScanLine,
  School,
  ScrollText,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Signature,
  Sparkles,
  Store,
  ToggleRight,
  TrendingUp,
  Upload,
  UserCog,
  UserSearch,
  Users,
  UsersRound,
  Video,
  Wallet,
  Zap,
  GitCompare,
  RefreshCw,
  type LucideIcon,
} from "lucide-react";

// One icon per nav destination. Keyed by href so both the top-level category and
// any child leaf resolve their own glyph. Every top-level category across the
// founder, investor, and admin workspaces is mapped here — anything unmapped
// falls back to Flag (see getWorkspaceNavIcon).
export const workspaceNavIconByHref: Record<string, LucideIcon> = {
  // ── Founder ───────────────────────────────────────────────────────────────
  "/founder": LayoutDashboard,
  "/founder/dashboard": LayoutDashboard,
  "/founder/onboarding": Rocket, // Stage 1 – Onboarding
  "/founder/readiness": ClipboardCheck, // Stage 2 – Preparation (also "Readiness checklist")
  // ── Stage 2 – Preparation children (distinct icon each) ───────────────────
  "/founder/stages/preparation": Map,
  "/founder/readiness/wizard": Gauge, // Capital Readiness Rating
  "/founder/readiness/data-room": FolderOpen,
  "/founder/preview": FileText, // One pager
  "/founder/business-plan": BookOpen,
  "/founder/pitch-deck": Presentation,
  "/founder/pitch-deck-analyzer": ScanLine,
  "/founder/market-claim": Crosshair,
  "/founder/financial-model": Calculator,
  "/founder/cap-table": PieChart,
  "/founder/valuation": Scale,
  "/founder/report": FileSearch, // AI diligence report
  "/founder/pitch-practice": Mic, // Prep & practice
  "/founder/investors": Megaphone, // Stage 3 – Marketing
  "/founder/deal-room": FlagTriangleRight, // Stage 4 – Closing
  "/founder/readiness/diligence": ShieldCheck,
  "/founder/readiness/documents": FileText,
  "/founder/readiness/missing": AlertTriangle,
  "/founder/documents": Files,
  "/founder/private-market": Store,
  "/founder/inbox": MessageSquare, // Communications
  "/founder/messages": MessageSquare,
  "/founder/updates": Mail,
  "/founder/calendar": Calendar,
  "/founder/schedule": CalendarClock,
  "/founder/events": PartyPopper,
  "/founder/tasks": CheckSquare,
  "/founder/help": Compass,
  "/founder/support": LifeBuoy,
  "/founder/reg-cf": Sparkles,
  "/founder/investors/outreach": MessageSquare,
  "/founder/investors/matches": Sparkles,
  "/founder/matches": Sparkles,
  "/founder/matching": GitCompare,
  "/founder/capital-raise": Rocket,
  "/founder/learning": GraduationCap,
  "/founder/analytics": LineChart,
  "/founder/journey": ListChecks,
  "/founder/actions": ListTodo,
  "/founder/settings": Settings,

  // ── Investor ─────────────────────────────────────────────────────────────
  "/investor/dashboard": LayoutDashboard,
  "/investor/onboarding": CircleUser, // Profile
  "/investor/verification": ShieldCheck, // Identity & accreditation
  "/investor/opportunities": Store, // Private Market
  "/investor/matches": Sparkles,
  "/investor/matching": GitCompare,
  "/investor/partner-score": Award,
  "/investor/watchlist": Heart,
  "/investor/interest-pipeline": TrendingUp,
  "/investor/deal-room": Handshake,
  "/investor/deals": FileCheck,
  "/investor/portfolio": PieChart,
  "/investor/spvs": Wallet,
  "/investor/activity": Activity,
  "/investor/actions": ListChecks,
  "/investor/tasks": CheckSquare,
  "/investor/inbox": MessageSquare, // Communications
  "/investor/messages": MessageSquare,
  "/investor/calendar": Calendar,
  "/investor/schedule": CalendarClock,
  "/investor/learning": School,
  "/investor/analytics": LineChart,
  "/investor/settings": Settings,

  // Shared
  "/credits": Coins,
  "/notifications": Bell,
  "/events": PartyPopper,

  // ── Admin ────────────────────────────────────────────────────────────────
  "/admin": LayoutDashboard,
  "/admin/dashboard": LayoutDashboard,
  "/admin/sales/contacts": Users,
  "/admin/ceo": Crown,
  "/admin/ir-funnel": Filter,
  "/admin/sales": ShoppingCart,
  "/admin/companies": Building,
  "/admin/investors": Users,
  "/admin/support": Headset,
  "/admin/founders-stuck": AlertTriangle,
  "/admin/prospect-intros": ArrowLeftRight,
  "/admin/playbook": HeartHandshake, // Investor Relations Hub
  "/admin/crm": MessageSquare, // IR CRM
  "/admin/crm/pipeline": TrendingUp,
  "/admin/crm/messages": MessageSquare,
  "/admin/crm/outreach": Rocket,
  "/admin/crm/unclassified": Filter,
  "/admin/crm/connectors": RefreshCw,
  "/admin/intro-requests": Forward,
  "/admin/marketplace": Store,
  "/admin/deal-rooms": DoorOpen,
  "/admin/spvs": Wallet,
  "/admin/matching": GitCompare,
  "/admin/matching/prospects": UserSearch,
  "/admin/outreach-qualification": Filter,
  "/admin/partner-scores": Award,
  "/admin/marketing": Megaphone, // Marketing Hub
  "/admin/events": PartyPopper, // Event Hub
  "/admin/events/email": Mail,
  "/admin/events/brochure": FileText,
  "/admin/voice": Mic, // Voice Hub
  "/admin/actions": ListTodo,
  "/admin/tasks": CheckSquare,
  "/admin/portfolio": PieChart,
  "/admin/readiness": Gauge,
  "/admin/data-room": ClipboardCheck,
  "/admin/learning": GraduationCap,
  "/admin/manual": BookOpen,
  "/admin/analytics": LineChart,
  "/admin/compliance": Shield,
  "/admin/diligence": FileCheck,
  "/admin/audit": ScrollText,
  "/admin/meetings": CalendarClock,
  "/admin/inbox": Inbox,
  "/admin/calendar": Calendar,
  "/admin/meet": Video,
  "/admin/signatures": Signature,
  "/admin/users/manage": UsersRound,
  "/admin/users/permissions": ShieldCheck,
  "/admin/feature-controls": ToggleRight,
  "/admin/billing": CreditCard,
  "/admin/accounts": Landmark,
  "/admin/profile": UserCog,
  "/admin/integrations": Settings, // System
  "/admin/queues": ListTodo,
  "/admin/automation": Zap,
  "/admin/reports": BarChart3,
  "/admin/imports": Upload,
  "/admin/insights": Sparkles,
  "/admin/system-health": Activity,
  "/admin/beta-operations": Activity,
  "/admin/page-builder-lab": LayoutDashboard,
  "/admin/funnels": Filter,
};

export function getWorkspaceNavIcon(href: string): LucideIcon {
  return workspaceNavIconByHref[href] ?? Flag;
}
