/**
 * Pricing page copy. New model: every TOOL is free; paid plans add DISTRIBUTION.
 * Free (readiness + all tools, matches shown but not who) → Basic $499 (up to 25,
 * one-pager, DIY outreach, spotlight) → Professional $1,000 (up to 100, live stage,
 * brokered intros, add-company $800) → Managed IR $3,500 (done-for-you, contact sales).
 */
export const pricing = {
  eyebrow: "Pricing",
  title: "Every tool is free. Pay to reach investors.",
  sub: "Readiness, valuation, the data room, and e-learning are free for everyone. Paid plans add distribution — revealing your matches, sending your one-pager, and the conference stage. No success fees, no carry, no commission after an introduction.",
  tiers: [
    {
      name: "Free",
      price: "$0",
      per: "forever",
      desc: "See how you match before you pay anything.",
      features: [
        "Every tool: CRR, valuation, data room, e-learning",
        "See that matches exist — count, sector, fit tier",
        "Investor identities hidden, no distribution",
        "Your qualification layer, prescored for you",
      ],
      cta: { label: "Start free", href: "/start?plan=free" },
      featured: false,
    },
    {
      name: "Basic",
      price: "$499",
      per: "/month",
      desc: "For founders starting the raise and building the list.",
      features: [
        "Everything in Free",
        "Up to 25 matched investors get your one-pager",
        "Event spotlight in the conference reel",
        "DIY outreach unlocked — you can now reach investors",
        "Fully self-serve",
      ],
      cta: { label: "Start on Basic", href: "/start?plan=basic" },
      featured: false,
    },
    {
      name: "Professional",
      price: "$1,000",
      per: "/month",
      badge: "Includes stage time",
      desc: "For founders actively in market who want the stage.",
      features: [
        "Everything in Basic",
        "Up to 100 matched investors",
        "Monthly live presentation slot",
        "Brokered intro requests",
        "Additional company accounts $800/mo",
      ],
      cta: { label: "Start on Professional", href: "/start?plan=professional" },
      featured: true,
    },
    {
      name: "Managed IR",
      price: "$3,500",
      per: "/month",
      badge: "Done-for-you",
      desc: "We run the raise for you. 3-month minimum.",
      features: [
        "Everything in Professional, uncapped",
        "We curate the list and your materials",
        "You review and approve",
        "Post-conference follow-up run for you",
        "Capacity-capped — talk to us",
      ],
      cta: { label: "Talk to us", href: "/start?plan=managed_ir" },
      featured: false,
      contactSales: true,
    },
  ],
  investorNote:
    "Investor accounts are free. Investors are never charged, and iCapOS takes no fee from either side of an introduction.",
  billingNote:
    "Billing & refunds. Every tool is free — start on the Free plan and see your matches before you pay. A paid plan begins delivering the moment you subscribe: distribution of your materials to matched investors in the iCFO network. Because those services are rendered immediately, subscriptions are billed monthly and are non-refundable, including partial periods. Cancel any time to stop future billing; access continues through the end of the paid period.",
  comparison: {
    title: "Side by side",
    sub: "Every tool is free. What you pay for is distribution.",
    cols: ["Free", "Basic · $499", "Professional · $1,000"],
    rows: [
      { k: "All tools (CRR, valuation, data room, e-learning)", vals: ["Included", "Included", "Included"] },
      { k: "See matches (count · sector · fit tier)", vals: ["Included", "Included", "Included"] },
      { k: "Investor identities revealed", vals: ["—", "Included", "Included"] },
      { k: "One-pager to matched investors", vals: ["—", "up to 25", "up to 100"] },
      { k: "DIY outreach", vals: ["—", "Included", "Included"] },
      { k: "Conference presence", vals: ["—", "Spotlight reel", "Live presentation slot"] },
      { k: "Brokered intro requests", vals: ["—", "—", "Included"] },
      { k: "Additional company accounts", vals: ["—", "—", "$800/mo"] },
      { k: "Success fees or commission", vals: ["None", "None", "None"] },
    ],
    note: "Managed IR — $3,500/mo, 3-month minimum — is done-for-you: we curate the list and materials, you approve, we run follow-up. Talk to us.",
  },
  crossLink: { label: "Not sure which plan? Start free with the readiness rating", href: "/readiness" },
  faq: {
    eyebrow: "Questions",
    title: "Before you subscribe.",
    items: [
      { q: "Is there a sales call?", a: "Not for Free, Basic, or Professional — those are self-serve start to finish. Managed IR is done-for-you, so it starts with a conversation. You can book a 30-minute walkthrough of the self-serve plans if you'd find it useful, but nothing requires it." },
      { q: "What do I get for free?", a: "Every tool — Capital Readiness Rating, valuation, the data room, and e-learning — plus you can see that matches exist (their count, sector, and fit tier). You just can't see who they are or reach them until you're on a paid plan." },
      { q: "Why “up to” 25 and 100?", a: "Investors set their own monthly acceptance caps. When the right-fit investors for your company have hit their limit that month, your list is shorter — which is what keeps response rates from collapsing." },
      { q: "Does iCapOS make introductions?", a: "On Professional, iCapOS passes along brokered introduction requests. It distributes your materials to matched investors; it does not recommend or vouch for anyone." },
      { q: "Do you take a percentage of what I raise?", a: "Never. The subscription is the entire commercial relationship." },
      { q: "Can I cancel?", a: "Any time, from your account settings. Your rating and materials stay accessible through the end of the paid period, and Free stays free." },
      { q: "What material do I need to have ready?", a: "Nothing. No deck, no model, no cap table, no investor list. The platform builds each of those with you — readiness is what iCapOS produces, not what it requires. Start free with whatever you have today." },
    ],
  },
} as const;
