import { PROFILES, CANONICAL_INSTITUTIONAL } from "@/lib/crr/profiles";

/** The public estimator shows the canonical (institutional) weighting. */
const W = PROFILES[CANONICAL_INSTITUTIONAL];

/**
 * Readiness page copy — ported VERBATIM from icapos-site-mock.html (spec §6, §13).
 * Weightings are imported from lib/crr/profiles.ts (the single source of truth) —
 * not hardcoded — and mapped onto the five display dimensions.
 */
export const readiness = {
  hero: {
    eyebrow: "Capital Readiness Rating",
    title: "Rated first — that's why the network opens.",
    sub: "A structured score across the five dimensions investors screen on, with an ordered list of what to sharpen. The rating is investor-facing quality control: nothing unrated goes out, which is why the network takes our calls.",
    cta: { label: "See your score band", href: "/assessment" },
    compliance: "The rating is an assessment tool. It is not investment advice, a valuation, a credit opinion, or any indication that capital will be raised.",
  },
  sample: {
    title: "Your rating",
    badge: "Sample",
    score: "0",
    band: "Developing",
    dimensions: [
      { label: "Narrative & positioning", desc: "Clear problem, weak differentiation", score: 78 },
      { label: "Financial model", desc: "No three-statement model on file", score: 41 },
      { label: "Traction evidence", desc: "Revenue shown, retention missing", score: 66 },
      { label: "Cap table & structure", desc: "Unpriced notes not modeled", score: 48 },
      { label: "Team & governance", desc: "No board or advisory structure", score: 71 },
    ],
    foot: "Two items to address first · Sample output",
  },
  analyzer: {
    eyebrow: "AI analysis",
    title: "Describe your company. Get a rating back.",
    sub: "Write a few sentences the way you'd explain the business to someone at a conference. The analyzer scores it on the same five dimensions and tells you what's missing.",
    chips: ["Try a pre-seed example", "Try a Series A example"],
    cta: "Analyze my company",
    disclaimer: "Analysis is generated by AI from what you write and is indicative only. It is not your official Capital Readiness Rating, not investment advice, and not a prediction of any funding outcome.",
  },
  estimator: {
    eyebrow: "Try it",
    title: "Estimate your rating in thirty seconds.",
    sub: "Move each slider to where you honestly are today. This is an indicative estimate using the published weightings — not your actual rating, which is generated from your real materials.",
    dimensions: [
      { label: "Narrative & positioning", weight: W.narrative, desc: "Problem clarity, differentiation, market framing", value: 70 },
      { label: "Financial model", weight: W.financial, desc: "Model completeness, assumptions, use of proceeds", value: 45 },
      { label: "Traction evidence", weight: W.traction, desc: "Revenue, retention, pipeline, verifiability", value: 60 },
      { label: "Cap table & structure", weight: W.capTable, desc: "Ownership, prior instruments, option pool", value: 50 },
      { label: "Team & governance", weight: W.team, desc: "Founder coverage, key hires, board, reporting", value: 65 },
    ],
    estimated: 58,
    band: "Developing",
    workOn: "Work on these first",
    cta: { label: "Get your real rating", href: "/start" },
    disclaimer: "Estimator only. Not a valuation, credit opinion, or prediction of any funding outcome.",
  },
  measures: {
    eyebrow: "What it measures",
    title: "Five dimensions, weighted toward what gets screened first.",
    cols: ["Dimension", "What it looks at", "Weight"],
    rows: [
      { label: "Narrative & positioning", looks: "Problem clarity, differentiation, market framing, the raise story", weight: W.narrative },
      { label: "Financial model", looks: "Model completeness, assumption quality, use of proceeds, runway", weight: W.financial },
      { label: "Traction evidence", looks: "Revenue, retention, pipeline, and whether the numbers are verifiable", weight: W.traction },
      { label: "Cap table & structure", looks: "Ownership, prior instruments, option pool, entity and jurisdiction", weight: W.capTable },
      { label: "Team & governance", looks: "Founder coverage, key hires, board, advisers, reporting discipline", weight: W.team },
    ],
    note: "Weightings shown are illustrative of the current rubric and are periodically recalibrated.",
  },
  getBack: {
    eyebrow: "What you get back",
    title: "A score is only useful if it tells you what to do next.",
    items: [
      { n: "01", h: "Your band and breakdown", p: "An overall rating out of 100, your band, and a per-dimension score showing which part is dragging the total down." },
      { n: "02", h: "An ordered fix list", p: "Items ordered by how much each one is holding the score down, so you can start with what matters rather than what's quickest." },
      { n: "03", h: "Re-scoring as you go", p: "Upload the revised model or cap table and re-run. The rating updates, and so does how you rank in matching." },
    ],
    // Required §3 cross-links: Readiness → Founders and Pricing, after the fix-list.
    founderCta: { label: "See what founders get", href: "/founders" },
    pricingCta: { label: "Compare the plans", href: "/pricing" },
    privacy: "Your rating is private. It is visible to you and to iCapOS. It is never published, and it is never shared with an investor unless you choose to share it.",
  },
  closing: {
    title: "Rough deck? Start anyway.",
    sub: "The rating is built to be run early. That's the point of it.",
    cta: { label: "See your score band", href: "/assessment" },
  },
} as const;
