#!/usr/bin/env node
// build:emails — compile the MJML masters and emit an idempotent seed migration
// (build spec §4). Run locally after `npm install --save-dev mjml`:
//
//   npm run build:emails
//
// For each master it: reads the .mjml, validates every {{token}} against the
// schema (mirrors src/lib/email/template-schema.ts — kept in lockstep with its
// tests), injects locked brand tokens at compile time, compiles MJML → HTML, and
// writes supabase/migrations/<ts>_seed_email_masters.sql that upserts the three
// masters. Review and apply that migration like any other. The build FAILS if any
// template omits the mandatory unsubscribe footer or references an unknown slot.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const TPL_DIR = join(ROOT, "src/lib/email/templates");

// Brand tokens injected at compile time (mirror of src/lib/email/brand.ts).
const APP_URL = (process.env.NEXT_PUBLIC_APP_URL ?? "https://icapos.com").replace(/\/+$/, "");
const BRAND_TOKENS = {
  logo: process.env.EMAIL_LOGO_URL ?? `${APP_URL}/email-logo.png`,
};

// Send-time tokens the send layer fills per recipient — legitimately present
// without a matching slot.
const SEND_TIME_TOKENS = ["unsubscribe_url", "view_in_browser_url", "first_name", "last_name", "company", "email"];
const REQUIRED_FOOTER_TOKENS = ["unsubscribe_url"];

const TOKEN_RE = /\{\{\s*([a-z0-9_]+)\s*\}\}/gi;
const tokensIn = (s) => [...new Set([...s.matchAll(TOKEN_RE)].map((m) => m[1].toLowerCase()))];

function validate(mjml, schema) {
  const errors = [];
  const known = new Set([
    ...schema.slots.map((s) => s.key.toLowerCase()),
    ...schema.locked.map((l) => l.toLowerCase()),
    ...SEND_TIME_TOKENS,
  ]);
  const used = tokensIn(mjml);
  for (const t of used) if (!known.has(t)) errors.push(`uses {{${t}}} but no slot/locked/send token defines it`);
  for (const r of REQUIRED_FOOTER_TOKENS) if (!used.includes(r)) errors.push(`missing mandatory footer token {{${r}}}`);
  for (const slot of schema.slots) {
    if (slot.required && !used.includes(slot.key.toLowerCase())) errors.push(`required slot "${slot.key}" never appears`);
  }
  return errors;
}

function sqlLiteral(s) {
  return `'${String(s).replace(/'/g, "''")}'`;
}

async function main() {
  let mjml2html;
  try {
    ({ default: mjml2html } = await import("mjml"));
  } catch {
    console.error("mjml is not installed. Run: npm install --save-dev mjml");
    process.exit(1);
  }

  const manifest = JSON.parse(readFileSync(join(TPL_DIR, "manifest.json"), "utf8"));
  const rows = [];
  const problems = [];

  for (const master of manifest.masters) {
    const rawMjml = readFileSync(join(TPL_DIR, `${master.slug}.mjml`), "utf8");

    const errs = validate(rawMjml, master.schema);
    if (errs.length) {
      problems.push(`• ${master.name}:\n   - ${errs.join("\n   - ")}`);
      continue;
    }

    // Inject locked brand tokens before compile; content + send tokens remain.
    let branded = rawMjml;
    for (const [key, value] of Object.entries(BRAND_TOKENS)) {
      branded = branded.replaceAll(new RegExp(`\\{\\{\\s*${key}\\s*\\}\\}`, "gi"), value);
    }

    const { html, errors } = mjml2html(branded, { validationLevel: "strict" });
    if (errors && errors.length) {
      problems.push(`• ${master.name}: MJML errors — ${errors.map((e) => e.message).join("; ")}`);
      continue;
    }

    rows.push({
      name: master.name,
      description: master.description,
      mjml_source: rawMjml,
      compiled_html: html,
      placeholder_schema: JSON.stringify(master.schema),
    });
  }

  if (problems.length) {
    console.error("build:emails failed:\n" + problems.join("\n"));
    process.exit(1);
  }

  const ts = new Date().toISOString().replace(/[-:T]/g, "").slice(0, 14);
  const values = rows
    .map(
      (r) =>
        `  (${sqlLiteral(r.name)}, ${sqlLiteral(r.description)}, ${sqlLiteral(r.mjml_source)}, ${sqlLiteral(
          r.compiled_html,
        )}, ${sqlLiteral(r.placeholder_schema)}::jsonb)`,
    )
    .join(",\n");

  const sql = `-- Auto-generated by scripts/build-emails.mjs — do not edit by hand.
-- Re-run \`npm run build:emails\` to regenerate. Idempotent via on conflict (name).

insert into public.email_template_masters (name, description, mjml_source, compiled_html, placeholder_schema)
values
${values}
on conflict (name) do update set
  description = excluded.description,
  mjml_source = excluded.mjml_source,
  compiled_html = excluded.compiled_html,
  placeholder_schema = excluded.placeholder_schema,
  updated_at = now();
`;

  const outPath = join(ROOT, "supabase/migrations", `${ts}_seed_email_masters.sql`);
  writeFileSync(outPath, sql);
  console.log(`Compiled ${rows.length} masters → ${outPath}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
