import PDFDocument from "pdfkit";
import type { AdminReportFilters, AdminReportPayload } from "@/lib/reports/admin-reports";
import { buildDueDiligencePortfolioPdf } from "@/lib/reports/portfolio-diligence-pdf";

type PdfDoc = InstanceType<typeof PDFDocument>;

type DueDiligenceRow = Record<string, unknown>;

export type PdfExportContext = {
  generatedBy: string;
};

function formatFilters(filters: AdminReportFilters): string[] {
  const lines: string[] = [];
  if (filters.dateFrom) lines.push(`Date from: ${filters.dateFrom}`);
  if (filters.dateTo) lines.push(`Date to: ${filters.dateTo}`);
  if (filters.companyId) lines.push(`Company ID: ${filters.companyId}`);
  if (filters.founderId) lines.push(`Founder ID: ${filters.founderId}`);
  if (filters.investorId) lines.push(`Investor ID: ${filters.investorId}`);
  if (filters.severity) lines.push(`Compliance severity: ${filters.severity}`);
  if (filters.reviewStatus) lines.push(`Review status: ${filters.reviewStatus}`);
  if (filters.spvStatus) lines.push(`SPV status: ${filters.spvStatus}`);
  if (filters.operationalReadinessStatus) {
    lines.push(`Operational readiness: ${filters.operationalReadinessStatus}`);
  }
  if (filters.closingReviewStatus) lines.push(`Closing review: ${filters.closingReviewStatus}`);
  if (lines.length === 0) {
    lines.push("No filters applied (full platform snapshot within export limits).");
  }
  return lines;
}

function ensureSpace(doc: PdfDoc, height: number) {
  const bottom = doc.page.height - doc.page.margins.bottom;
  if (doc.y + height > bottom) {
    doc.addPage();
  }
}

function sectionTitle(doc: PdfDoc, title: string) {
  ensureSpace(doc, 28);
  doc.moveDown(0.5);
  doc.fontSize(12).fillColor("#1e293b").text(title, { underline: true });
  doc.moveDown(0.35);
  doc.fontSize(9).fillColor("#334155");
}

function bodyText(doc: PdfDoc, text: string) {
  ensureSpace(doc, 16);
  doc.text(text, { lineGap: 2 });
}

function bulletList(doc: PdfDoc, items: string[]) {
  for (const item of items) {
    ensureSpace(doc, 14);
    doc.text(`• ${item}`, { indent: 8, lineGap: 1 });
  }
}

function drawTable(
  doc: PdfDoc,
  headers: string[],
  rows: string[][],
  columnWidths: number[],
) {
  const startX = doc.page.margins.left;
  const rowHeight = 16;
  const headerHeight = 18;

  const drawRow = (cells: string[], y: number, bold: boolean) => {
    doc.font(bold ? "Helvetica-Bold" : "Helvetica").fontSize(8);
    let x = startX;
    for (let i = 0; i < cells.length; i++) {
      const cell = cells[i] ?? "";
      const width = columnWidths[i] ?? 60;
      doc.text(cell, x, y, { width, height: rowHeight, ellipsis: true });
      x += width;
    }
  };

  ensureSpace(doc, headerHeight + rowHeight * Math.min(rows.length, 3));
  const headerY = doc.y;
  drawRow(headers, headerY, true);
  doc
    .moveTo(startX, headerY + headerHeight - 4)
    .lineTo(startX + columnWidths.reduce((a, b) => a + b, 0), headerY + headerHeight - 4)
    .strokeColor("#cbd5e1")
    .stroke();

  let y = headerY + headerHeight;
  for (const row of rows) {
    if (y + rowHeight > doc.page.height - doc.page.margins.bottom) {
      doc.addPage();
      y = doc.page.margins.top;
      drawRow(headers, y, true);
      y += headerHeight;
    }
    drawRow(row, y, false);
    y += rowHeight;
  }
  doc.y = y + 6;
}

/** Portfolio Due Diligence PDF (no single company). v2 layout lives in portfolio-diligence-pdf.ts. */
export async function buildDueDiligencePdf(
  payload: AdminReportPayload,
  context: PdfExportContext,
): Promise<Buffer> {
  return buildDueDiligencePortfolioPdf(payload, context);
}

const PDF_SPV_ROW_LIMIT = 40;

export async function buildSpvReadinessPdf(
  payload: AdminReportPayload,
  context: PdfExportContext,
): Promise<Buffer> {
  const rows = (payload.sections.spv_readiness_rows ?? []) as DueDiligenceRow[];
  const notificationTotals = (payload.sections.notification_type_totals ?? []) as DueDiligenceRow[];
  const summary = payload.summary;
  const generatedAt = new Date(payload.meta.generatedAt).toLocaleString();

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "LETTER" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).fillColor("#312e81").text("iCapOS", { align: "left" });
    doc.fontSize(14).fillColor("#0f172a").text("SPV Operational Readiness Report", { align: "left" });
    doc.moveDown(0.5);
    doc.fontSize(9).fillColor("#475569");
    doc.text(`Generated: ${generatedAt}`);
    doc.text(`Generated by: ${context.generatedBy}`);
    doc.text("Report type: spv_readiness (internal staff use only)");
    doc.moveDown(0.5);

    sectionTitle(doc, "Filters applied");
    bulletList(doc, formatFilters(payload.meta.filters));

    sectionTitle(doc, "Executive summary");
    bulletList(doc, [
      `SPVs included: ${summary.spvsIncluded ?? 0}`,
      `Total indicative participation: ${summary.totalIndicativeParticipation ?? 0}`,
      `Total participating investors: ${summary.totalInvestors ?? 0}`,
      `Average checklist readiness: ${summary.averageChecklistReadinessPct ?? 0}%`,
      `Average closing readiness: ${summary.averageClosingReadinessPct ?? 0}%`,
      `SPVs with pending blockers: ${summary.spvsWithPendingBlockers ?? 0}`,
      `Approved for closing: ${summary.spvsApprovedForClosing ?? 0}`,
      `Operationally closed: ${summary.spvsOperationallyClosed ?? 0}`,
    ]);

    if (notificationTotals.length > 0) {
      sectionTitle(doc, "SPV notification activity (counts by type)");
      bulletList(
        doc,
        notificationTotals.slice(0, 12).map(
          (row) => `${String(row.notification_type)}: ${String(row.count)}`,
        ),
      );
    }

    sectionTitle(doc, "SPV readiness table");
    const tableRows = rows.slice(0, PDF_SPV_ROW_LIMIT);
    if (tableRows.length === 0) {
      bodyText(doc, "No SPVs match the selected filters.");
    } else {
      if (rows.length > PDF_SPV_ROW_LIMIT) {
        bodyText(
          doc,
          `Showing first ${PDF_SPV_ROW_LIMIT} of ${rows.length} SPVs. Use JSON export for full data.`,
        );
        doc.moveDown(0.25);
      }
      drawTable(
        doc,
        ["SPV", "Co", "St", "Chk%", "Inv%", "Pkg%", "Cls%", "Closing", "Block"],
        tableRows.map((row) => [
          String(row.spv_name ?? "").slice(0, 18),
          String(row.company_name ?? "").slice(0, 14),
          String(row.spv_status ?? ""),
          String(row.checklist_readiness_pct ?? 0),
          String(row.investor_requirement_readiness_pct ?? 0),
          String(row.document_package_readiness_pct ?? 0),
          String(row.closing_readiness_pct ?? 0),
          String(row.closing_review_status ?? "").slice(0, 12),
          String(row.pending_blocker_count ?? 0),
        ]),
        [72, 72, 36, 36, 36, 36, 36, 72, 36],
      );
    }

    sectionTitle(doc, "Privacy & compliance disclaimer");
    doc.fontSize(8).fillColor("#64748b");
    bodyText(doc, payload.meta.privacyNotice);

    doc.end();
  });
}
