import PDFDocument from "pdfkit";
import type { AdminReportFilters, AdminReportPayload } from "@/lib/reports/admin-reports";

type PdfDoc = InstanceType<typeof PDFDocument>;

const PDF_COMPANY_ROW_LIMIT = 40;

type DueDiligenceRow = Record<string, unknown>;

export type PdfExportContext = {
  generatedBy: string;
};

function formatFilters(filters: AdminReportFilters): string[] {
  const lines: string[] = [];
  if (filters.dateFrom) lines.push(`Date from: ${filters.dateFrom}`);
  if (filters.dateTo) lines.push(`Date to: ${filters.dateTo}`);
  if (filters.companyId) lines.push(`Company ID: ${filters.companyId}`);
  if (filters.founderId) lines.push(`Founder ID: ${filters.founderId}`);
  if (filters.investorId) lines.push(`Investor ID: ${filters.investorId}`);
  if (filters.severity) lines.push(`Compliance severity: ${filters.severity}`);
  if (filters.reviewStatus) lines.push(`Review status: ${filters.reviewStatus}`);
  if (filters.spvStatus) lines.push(`SPV status: ${filters.spvStatus}`);
  if (filters.operationalReadinessStatus) {
    lines.push(`Operational readiness: ${filters.operationalReadinessStatus}`);
  }
  if (filters.closingReviewStatus) lines.push(`Closing review: ${filters.closingReviewStatus}`);
  if (lines.length === 0) {
    lines.push("No filters applied (full platform snapshot within export limits).");
  }
  return lines;
}

function ensureSpace(doc: PdfDoc, height: number) {
  const bottom = doc.page.height - doc.page.margins.bottom;
  if (doc.y + height > bottom) {
    doc.addPage();
  }
}

function sectionTitle(doc: PdfDoc, title: string) {
  ensureSpace(doc, 28);
  doc.moveDown(0.5);
  doc.fontSize(12).fillColor("#1e293b").text(title, { underline: true });
  doc.moveDown(0.35);
  doc.fontSize(9).fillColor("#334155");
}

function bodyText(doc: PdfDoc, text: string) {
  ensureSpace(doc, 16);
  doc.text(text, { lineGap: 2 });
}

function bulletList(doc: PdfDoc, items: string[]) {
  for (const item of items) {
    ensureSpace(doc, 14);
    doc.text(`• ${item}`, { indent: 8, lineGap: 1 });
  }
}

function drawTable(
  doc: PdfDoc,
  headers: string[],
  rows: string[][],
  columnWidths: number[],
) {
  const startX = doc.page.margins.left;
  const rowHeight = 16;
  const headerHeight = 18;

  const drawRow = (cells: string[], y: number, bold: boolean) => {
    doc.font(bold ? "Helvetica-Bold" : "Helvetica").fontSize(8);
    let x = startX;
    for (let i = 0; i < cells.length; i++) {
      const cell = cells[i] ?? "";
      const width = columnWidths[i] ?? 60;
      doc.text(cell, x, y, { width, height: rowHeight, ellipsis: true });
      x += width;
    }
  };

  ensureSpace(doc, headerHeight + rowHeight * Math.min(rows.length, 3));
  const headerY = doc.y;
  drawRow(headers, headerY, true);
  doc
    .moveTo(startX, headerY + headerHeight - 4)
    .lineTo(startX + columnWidths.reduce((a, b) => a + b, 0), headerY + headerHeight - 4)
    .strokeColor("#cbd5e1")
    .stroke();

  let y = headerY + headerHeight;
  for (const row of rows) {
    if (y + rowHeight > doc.page.height - doc.page.margins.bottom) {
      doc.addPage();
      y = doc.page.margins.top;
      drawRow(headers, y, true);
      y += headerHeight;
    }
    drawRow(row, y, false);
    y += rowHeight;
  }
  doc.y = y + 6;
}

function sumRows(companies: DueDiligenceRow[], key: string): number {
  return companies.reduce((total, row) => total + (Number(row[key]) || 0), 0);
}

export async function buildDueDiligencePdf(
  payload: AdminReportPayload,
  context: PdfExportContext,
): Promise<Buffer> {
  const companies = (payload.sections.company_diligence ?? []) as DueDiligenceRow[];
  const topRisk = (payload.sections.top_risk_companies ?? []) as DueDiligenceRow[];
  const distribution = (payload.sections.readiness_distribution ?? []) as DueDiligenceRow[];
  const summary = payload.summary;
  const generatedAt = new Date(payload.meta.generatedAt).toLocaleString();

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "LETTER" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).fillColor("#312e81").text("CapitalOS", { align: "left" });
    doc.fontSize(14).fillColor("#0f172a").text("Due Diligence Report", { align: "left" });
    doc.moveDown(0.5);
    doc.fontSize(9).fillColor("#475569");
    doc.text(`Generated: ${generatedAt}`);
    doc.text(`Generated by: ${context.generatedBy}`);
    doc.text("Report type: due_diligence (internal staff use only)");
    doc.moveDown(0.5);

    sectionTitle(doc, "Filters applied");
    bulletList(doc, formatFilters(payload.meta.filters));

    sectionTitle(doc, "Executive summary");
    bulletList(doc, [
      `Companies included: ${summary.companiesIncluded ?? 0}`,
      `Average readiness score: ${summary.averageReadinessScore ?? "—"}`,
      `Companies with open compliance events: ${summary.companiesWithOpenCompliance ?? 0}`,
      `Total expressed interests: ${summary.totalExpressedInterests ?? 0}`,
      `Total indicative pledge (aggregate): ${summary.totalIndicativePledge ?? 0}`,
      `Companies missing pitch deck: ${summary.companiesMissingPitchDeck ?? 0}`,
    ]);

    sectionTitle(doc, "Readiness score summary");
    if (distribution.length > 0) {
      bulletList(
        doc,
        distribution.map(
          (row) => `${String(row.bucket)}: ${String(row.count)} companies`,
        ),
      );
    } else {
      bodyText(doc, "No readiness distribution data for current filters.");
    }
    if (topRisk.length > 0) {
      doc.moveDown(0.25);
      bodyText(doc, "Top risk companies:");
      bulletList(
        doc,
        topRisk.slice(0, 8).map(
          (row) =>
            `${String(row.company_name)} — risk ${String(row.risk_score)}, readiness ${String(row.latest_readiness_score ?? "—")}, open compliance ${String(row.open_compliance_events)}`,
        ),
      );
    }

    sectionTitle(doc, "Document status (aggregate)");
    bulletList(doc, [
      `Total documents (across companies): ${sumRows(companies, "document_count")}`,
      `Companies with pitch deck: ${companies.filter((c) => c.pitch_deck_present).length}`,
      `Companies without pitch deck: ${companies.filter((c) => !c.pitch_deck_present).length}`,
      `Approved document records: ${sumRows(companies, "documents_approved_count")}`,
    ]);

    sectionTitle(doc, "Remediation summary");
    bulletList(doc, [
      `Open remediation tasks: ${sumRows(companies, "remediation_open")}`,
      `Completed remediation tasks: ${sumRows(companies, "remediation_completed")}`,
      `High-priority open tasks: ${sumRows(companies, "remediation_high_priority_open")}`,
    ]);

    sectionTitle(doc, "Compliance risk summary");
    bulletList(doc, [
      `Open compliance events: ${sumRows(companies, "open_compliance_events")}`,
      `Flagged outreach/social/message indicators: ${sumRows(companies, "flagged_outreach_social_message_indicators")}`,
    ]);

    sectionTitle(doc, "Investor-readiness indicators (aggregate)");
    bulletList(doc, [
      `Expressed interests: ${summary.totalExpressedInterests ?? sumRows(companies, "expressed_interest_count")}`,
      `Indicative pledge total: ${summary.totalIndicativePledge ?? sumRows(companies, "indicative_pledge_total")}`,
      `Intro requests: ${sumRows(companies, "intro_request_count")}`,
      `Message threads: ${sumRows(companies, "message_thread_count")}`,
      `Scheduled meetings: ${sumRows(companies, "meetings_scheduled_count")}`,
      `Learning modules completed: ${sumRows(companies, "learning_modules_completed")}`,
    ]);

    sectionTitle(doc, "Company diligence table");
    const tableRows = companies.slice(0, PDF_COMPANY_ROW_LIMIT);
    if (tableRows.length === 0) {
      bodyText(doc, "No companies match the selected filters.");
    } else {
      if (companies.length > PDF_COMPANY_ROW_LIMIT) {
        bodyText(
          doc,
          `Showing first ${PDF_COMPANY_ROW_LIMIT} of ${companies.length} companies. Use JSON export for full data.`,
        );
        doc.moveDown(0.25);
      }
      drawTable(
        doc,
        ["Company", "Ready", "Onb%", "Docs", "Rem", "Cmp", "Int", "Pledge"],
        tableRows.map((row) => [
          String(row.company_name ?? "").slice(0, 22),
          String(row.latest_readiness_score ?? "—"),
          String(row.onboarding_progress_percent ?? "—"),
          String(row.document_count ?? 0),
          String(row.remediation_open ?? 0),
          String(row.open_compliance_events ?? 0),
          String(row.expressed_interest_count ?? 0),
          String(row.indicative_pledge_total ?? 0),
        ]),
        [110, 36, 36, 32, 32, 32, 32, 48],
      );
    }

    sectionTitle(doc, "Privacy disclaimer");
    doc.fontSize(8).fillColor("#64748b");
    bodyText(
      doc,
      payload.meta.privacyNotice +
        " This PDF does not include private investor contact details, message bodies, Google OAuth tokens, or external calendar event identifiers. For legal opinions, SEC filings, or investor distribution, use dedicated workflows outside this export.",
    );

    doc.end();
  });
}

const PDF_SPV_ROW_LIMIT = 40;

export async function buildSpvReadinessPdf(
  payload: AdminReportPayload,
  context: PdfExportContext,
): Promise<Buffer> {
  const rows = (payload.sections.spv_readiness_rows ?? []) as DueDiligenceRow[];
  const notificationTotals = (payload.sections.notification_type_totals ?? []) as DueDiligenceRow[];
  const summary = payload.summary;
  const generatedAt = new Date(payload.meta.generatedAt).toLocaleString();

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "LETTER" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).fillColor("#312e81").text("CapitalOS", { align: "left" });
    doc.fontSize(14).fillColor("#0f172a").text("SPV Operational Readiness Report", { align: "left" });
    doc.moveDown(0.5);
    doc.fontSize(9).fillColor("#475569");
    doc.text(`Generated: ${generatedAt}`);
    doc.text(`Generated by: ${context.generatedBy}`);
    doc.text("Report type: spv_readiness (internal staff use only)");
    doc.moveDown(0.5);

    sectionTitle(doc, "Filters applied");
    bulletList(doc, formatFilters(payload.meta.filters));

    sectionTitle(doc, "Executive summary");
    bulletList(doc, [
      `SPVs included: ${summary.spvsIncluded ?? 0}`,
      `Total indicative participation: ${summary.totalIndicativeParticipation ?? 0}`,
      `Total participating investors: ${summary.totalInvestors ?? 0}`,
      `Average checklist readiness: ${summary.averageChecklistReadinessPct ?? 0}%`,
      `Average closing readiness: ${summary.averageClosingReadinessPct ?? 0}%`,
      `SPVs with pending blockers: ${summary.spvsWithPendingBlockers ?? 0}`,
      `Approved for closing: ${summary.spvsApprovedForClosing ?? 0}`,
      `Operationally closed: ${summary.spvsOperationallyClosed ?? 0}`,
    ]);

    if (notificationTotals.length > 0) {
      sectionTitle(doc, "SPV notification activity (counts by type)");
      bulletList(
        doc,
        notificationTotals.slice(0, 12).map(
          (row) => `${String(row.notification_type)}: ${String(row.count)}`,
        ),
      );
    }

    sectionTitle(doc, "SPV readiness table");
    const tableRows = rows.slice(0, PDF_SPV_ROW_LIMIT);
    if (tableRows.length === 0) {
      bodyText(doc, "No SPVs match the selected filters.");
    } else {
      if (rows.length > PDF_SPV_ROW_LIMIT) {
        bodyText(
          doc,
          `Showing first ${PDF_SPV_ROW_LIMIT} of ${rows.length} SPVs. Use JSON export for full data.`,
        );
        doc.moveDown(0.25);
      }
      drawTable(
        doc,
        ["SPV", "Co", "St", "Chk%", "Inv%", "Pkg%", "Cls%", "Closing", "Block"],
        tableRows.map((row) => [
          String(row.spv_name ?? "").slice(0, 18),
          String(row.company_name ?? "").slice(0, 14),
          String(row.spv_status ?? ""),
          String(row.checklist_readiness_pct ?? 0),
          String(row.investor_requirement_readiness_pct ?? 0),
          String(row.document_package_readiness_pct ?? 0),
          String(row.closing_readiness_pct ?? 0),
          String(row.closing_review_status ?? "").slice(0, 12),
          String(row.pending_blocker_count ?? 0),
        ]),
        [72, 72, 36, 36, 36, 36, 36, 72, 36],
      );
    }

    sectionTitle(doc, "Privacy & compliance disclaimer");
    doc.fontSize(8).fillColor("#64748b");
    bodyText(doc, payload.meta.privacyNotice);

    doc.end();
  });
}
