import type { SopEntry } from "./types";

/**
 * Admin Operations Manual — 57 SOPs across 14 parts.
 *
 * Single source of truth for both the /admin/manual page and the assistant's
 * SOP answers. Each entry uses the same template: summary (Purpose), permission
 * (Who can do it), steps (Before you start + Steps), behindScenes, reversibility,
 * and warnings. Part A (account lifecycle) is the most detailed.
 *
 * Permission slugs map to src/lib/rbac/constants.ts. superAdminOnly entries are
 * hidden from non-super-admins entirely; permission gaps elsewhere are shown but
 * locked. planned entries describe procedures whose backing feature is not built
 * yet, so staff don't hunt for buttons that don't exist.
 */
export const ADMIN_SOPS: SopEntry[] = [
  // ── Part A · Account & access lifecycle ─────────────────────────────────────
  {
    id: 1,
    part: "A",
    title: "Founder onboarding",
    summary: "How a founder account comes into being and reaches an active workspace.",
    permission: null,
    keywords: ["founder", "onboarding", "sign up", "signup", "register", "new founder", "create company", "join"],
    steps: [
      "Founder self-signs up at /auth/sign-up and selects the Founder role.",
      "Supabase Auth creates the user; the handle_new_user trigger inserts their profiles row automatically.",
      "Founder completes onboarding (company profile), which unlocks documents, readiness scoring, and admin review.",
      "No admin action is required unless the founder reports a stuck step — then verify their profile and company link in Admin → User management.",
    ],
    behindScenes:
      "Profile creation is driven by the on_auth_user_created database trigger, not by app code. The founder's company is created during onboarding and linked via companies.founder_id.",
    reversibility: "If onboarding is abandoned, the account can be deactivated or deleted (see SOPs 5 and 7).",
    warnings: ["Never hand-create a profiles row — it must come from the auth trigger, or it will drift from Supabase Auth."],
  },
  {
    id: 2,
    part: "A",
    title: "Investor onboarding & approval",
    summary: "How an investor signs up and gets approved for restricted features.",
    permission: "manage_investors",
    keywords: ["investor", "onboarding", "sign up", "signup", "approve investor", "investor approval", "accredited"],
    steps: [
      "Investor self-signs up and selects the Investor role; the auth trigger creates their profile.",
      "They complete the investor profile; status starts as pending.",
      "Open Admin → Investors, review the profile, and approve or reject.",
      "Approval unlocks SPV browsing and marketplace actions. Approval is never automatic or guaranteed.",
    ],
    behindScenes: "Approval status gates investor features through the InvestorFeatureGate and server-side access checks.",
    reversibility: "Approval can be revoked; the investor returns to a restricted state.",
  },
  {
    id: 3,
    part: "A",
    title: "Create an internal staff account",
    summary: "Invite a new admin or analyst by email.",
    permission: "manage_users",
    keywords: ["create account", "invite", "staff", "add admin", "add analyst", "new admin", "new user", "invite user"],
    steps: [
      "Go to Admin → User management.",
      "Use the staff invite action and enter the person's email.",
      "Choose their role (admin or analyst).",
      "Send. They receive an email invite; accepting it creates a real Supabase Auth user, and the trigger creates their profile.",
    ],
    behindScenes:
      "Invites use Supabase inviteUserByEmail, so the account is a genuine auth user from the start — this is the clean creation path that never drifts.",
    reversibility: "An unaccepted invite can be revoked; an accepted one is managed like any account.",
    warnings: ["Grant admin only when needed. Prefer analyst for read-heavy roles, and use RBAC (SOP 11) for finer control."],
  },
  {
    id: 4,
    part: "A",
    title: "Edit a user — change role or profile",
    summary: "Change a user's workspace role or update profile fields.",
    permission: "assign_roles",
    keywords: ["edit user", "change role", "update profile", "promote", "demote", "role change", "reassign role"],
    steps: [
      "Admin → User management, find the user.",
      "Pick the new role in the row's role dropdown and click Save.",
      "The change takes effect on the user's next page load and is written to the audit log.",
    ],
    behindScenes: "Role lives in profiles.role and is enforced by the middleware (src/proxy.ts) on every protected request.",
    reversibility: "Fully reversible — change the role back at any time.",
    warnings: [
      "You cannot modify a super admin account.",
      "You cannot demote the last active admin (lockout guard) — promote someone else first.",
    ],
  },
  {
    id: 5,
    part: "A",
    title: "Deactivate an account",
    summary: "Revoke a user's access immediately, reversibly. The default safe choice.",
    permission: "manage_users",
    keywords: ["deactivate", "disable", "suspend", "revoke access", "turn off account", "block login"],
    steps: [
      "Admin → User management, find the user.",
      "Click Deactivate on their row.",
      "Access is blocked immediately; all their data is preserved.",
    ],
    behindScenes: "Sets profiles.is_active = false. The user can no longer use the workspace, but nothing is deleted. Logged to the audit trail.",
    reversibility: "Fully reversible — Reactivate restores access (SOP 6).",
    warnings: ["You cannot deactivate the last active admin — promote another admin first."],
  },
  {
    id: 6,
    part: "A",
    title: "Reactivate an account",
    summary: "Restore a previously deactivated account.",
    permission: "manage_users",
    keywords: ["reactivate", "re-enable", "restore account", "unsuspend", "re-activate", "enable user"],
    steps: [
      "Admin → User management, switch to the Inactive tab.",
      "Find the user and click Reactivate.",
      "Access is restored immediately.",
    ],
    behindScenes: "Sets profiles.is_active = true and logs the reactivation.",
    reversibility: "Reversible — deactivate again at any time.",
  },
  {
    id: 7,
    part: "A",
    title: "Permanently delete an account",
    summary: "Irreversibly remove an account and everything it owns. For genuine purges only.",
    permission: "manage_users",
    keywords: ["delete", "permanently delete", "remove user", "erase", "purge", "gdpr delete", "hard delete"],
    steps: [
      "Prefer Deactivate (SOP 5) unless this is a true purge or erasure request.",
      "Admin → User management, find the user, click the trash icon.",
      "Review the blast radius — the counts of companies, documents, deal rooms, etc. that will cascade-delete.",
      "Type the user's email to confirm, then click Delete permanently.",
    ],
    behindScenes:
      "Deletes the Supabase Auth user; the profile and owned records cascade via foreign keys. Audit references are set null, not deleted, so history survives.",
    reversibility: "Irreversible. There is no undo — the cascade removes owned data.",
    warnings: [
      "Blocked for your own account, super admins, and the last active admin.",
      "Always confirm the blast radius before typing the email.",
    ],
  },
  {
    id: 8,
    part: "A",
    title: "Resend an invite or send a magic link",
    summary: "Re-issue access to a user who lost or never received their invite.",
    permission: "manage_users",
    planned: true,
    keywords: ["resend invite", "magic link", "re-invite", "resend", "lost invite", "login link"],
    steps: [
      "Planned: a Resend action on invited/active rows in User management.",
      "Until then, deactivate and re-invite, or ask the user to use the password-reset flow on the sign-in page.",
    ],
    warnings: ["Backing feature not yet built — see the sign-in page's self-service reset as the interim path."],
  },
  {
    id: 9,
    part: "A",
    title: "Reset a user's password",
    summary: "Help a user regain access when they're locked out.",
    permission: "manage_users",
    planned: true,
    keywords: ["reset password", "password", "locked out", "forgot password", "cannot log in"],
    steps: [
      "Planned: an admin-initiated reset from User management.",
      "Until then, direct the user to the self-service 'Forgot password' link on /auth/sign-in.",
    ],
    warnings: ["Backing feature not yet built — use the self-service reset for now."],
  },
  {
    id: 10,
    part: "A",
    title: "Revoke active sessions",
    summary: "Force a user to re-authenticate everywhere.",
    permission: "manage_users",
    planned: true,
    keywords: ["revoke session", "sign out", "force logout", "kill session", "log out everywhere"],
    steps: [
      "Planned: a Revoke sessions action for incident response.",
      "Until then, deactivating the account (SOP 5) blocks workspace access immediately.",
    ],
    warnings: ["Backing feature not yet built — deactivate as the interim containment step."],
  },
  {
    id: 11,
    part: "A",
    title: "Manage RBAC roles & permissions",
    summary: "Assign granular internal permissions on top of the admin role.",
    permission: "assign_roles",
    keywords: ["rbac", "permissions", "internal role", "grant permission", "manager", "super admin", "assign role", "permission override"],
    steps: [
      "Go to Admin → User Permissions.",
      "Assign an internal role (regular_user, manager, admin, super_admin) or per-user permission overrides.",
      "Save. Effective permissions resolve from role grants plus overrides.",
    ],
    behindScenes:
      "Internal RBAC (src/lib/rbac/) layers on the workspace role. Legacy staff without an RBAC row get LEGACY_STAFF_PERMISSIONS automatically (everything except manage_users and assign_roles).",
    reversibility: "Reversible — adjust roles or overrides anytime.",
    warnings: ["Only a super admin can grant manage_users or assign_roles."],
  },
  {
    id: 12,
    part: "A",
    title: "Resolve a profiles ↔ Supabase Auth drift",
    summary: "Fix the case where the admin user list disagrees with Supabase Auth.",
    permission: "manage_users",
    keywords: ["drift", "out of sync", "mismatch", "supabase auth", "orphan profile", "sync issue", "count mismatch"],
    steps: [
      "Confirm the drift: compare Admin → User management counts with the Supabase Auth users list.",
      "The structural fix is migration 20260620002 — it ties profiles.id to auth.users(id) with ON DELETE CASCADE and cleans orphans.",
      "If a one-off orphan appears, delete the orphaned profiles row (no matching auth user) after verifying.",
    ],
    behindScenes:
      "Root cause was a missing foreign key from profiles.id to auth.users. With the cascade FK in place, deletes stay consistent and drift can't recur.",
    reversibility: "Data cleanup is not reversible — verify before deleting any row.",
    warnings: ["Run integrity migrations on staging first, and back up before applying to production (SOP 36)."],
  },
  {
    id: 13,
    part: "A",
    title: "Audit trail review & account recovery",
    summary: "See who did what, and recover from a mistaken account action.",
    permission: "view_audit_logs",
    keywords: ["audit", "audit log", "who changed", "history", "recover", "undo", "activity log", "trail"],
    steps: [
      "User management shows a recent audit trail (role changes, deactivations, invites, deletions).",
      "For a deactivation, simply Reactivate (SOP 6).",
      "For a permanent deletion, there is no undo — restore from a database backup if recovery is essential (SOP 36).",
    ],
    behindScenes: "Actions are written via writeAuditLog (e.g. admin.user_role_changed, admin.user_deactivated, admin.user_deleted).",
    reversibility: "Deactivations are reversible; deletions are not.",
  },

  // ── Part B · Subscriptions, billing & feature access ────────────────────────
  {
    id: 14,
    part: "B",
    title: "Set or change a user's plan",
    summary: "Move a founder between trial and paid plans.",
    permission: "manage_billing",
    keywords: ["plan", "subscription", "billing", "trial", "upgrade", "downgrade", "tier", "founder_basic", "professional"],
    steps: [
      "Open the user's billing/subscription record in the admin billing area.",
      "Select the target plan (founder_trial, founder_basic, founder_professional, etc.).",
      "Save; feature access updates per the plan's feature keys.",
    ],
    behindScenes: "Plans live in src/lib/subscriptions/plans.ts; gates are enforced by FounderFeatureGate / InvestorFeatureGate and server-side access checks.",
    reversibility: "Reversible — change the plan again as needed.",
  },
  {
    id: 15,
    part: "B",
    title: "Handle an upgrade request",
    summary: "Review and action a user's request to change plan or unlock a feature.",
    permission: "manage_billing",
    keywords: ["upgrade request", "request", "unlock", "plan change request", "approve upgrade"],
    steps: [
      "Open the upgrade_requests queue in the admin billing area.",
      "Review the requested plan or feature key and the user's context.",
      "Approve (apply the plan/feature) or decline with a note.",
    ],
    reversibility: "Reversible via plan/feature changes (SOPs 14, 16).",
  },
  {
    id: 16,
    part: "B",
    title: "Grant or revoke a feature",
    summary: "Toggle a specific feature for a user independent of their plan.",
    permission: "manage_billing",
    keywords: ["feature", "feature gate", "grant feature", "revoke feature", "entitlement", "access feature"],
    steps: [
      "Identify the feature key (e.g. ai_diligence, capital_raise, analytics).",
      "Adjust the user's entitlement in the billing/access admin.",
      "Confirm the relevant FeatureGate now allows or blocks the area.",
    ],
    behindScenes: "Feature keys are defined alongside plans; access is checked in src/lib/subscriptions/access.ts and founder-access.ts.",
    reversibility: "Reversible.",
  },

  // ── Part C · Founder workflow administration ────────────────────────────────
  {
    id: 17,
    part: "C",
    title: "Approve a founder stage-advancement request",
    summary: "Move a founder forward through the journey gates (Qualify, Deploy, Optimize).",
    permission: "manage_companies",
    keywords: ["stage", "journey", "approve stage", "qualify", "deploy", "optimize", "advance", "gate", "stage approval"],
    steps: [
      "Open the admin approval queue for stage-advancement requests.",
      "Review the company's readiness and required documents for the target stage.",
      "Approve to unlock the next stage, or return with feedback.",
    ],
    behindScenes: "Gates are evaluated in src/lib/founder-journey/; approval flips the stage that FounderJourneyGate reads.",
    reversibility: "A stage can be reverted if approved in error.",
  },
  {
    id: 18,
    part: "C",
    title: "Review diligence documents & readiness",
    summary: "Assess a company's uploaded documents and readiness score.",
    permission: "review_documents",
    keywords: ["diligence", "documents", "readiness", "review documents", "readiness score", "document review"],
    steps: [
      "Open the company in the admin review area.",
      "Review uploaded documents against the required set.",
      "Confirm or recompute the readiness score; flag missing or weak items for remediation.",
    ],
    behindScenes: "Readiness falls back to computeReadinessScore when no AI score is present; document types are matched via the shared documents constant.",
    reversibility: "Assessments can be updated as documents change.",
  },
  {
    id: 19,
    part: "C",
    title: "Generate or review an AI diligence report",
    summary: "Produce or read the Claude-generated diligence report for a company.",
    permission: "manage_diligence",
    keywords: ["ai diligence", "diligence report", "claude report", "generate report", "ai report"],
    steps: [
      "Open the company's diligence area in the admin workspace.",
      "Trigger report generation (staff-only) or open the latest report.",
      "Review findings; reports degrade gracefully if ANTHROPIC_API_KEY is absent.",
    ],
    behindScenes: "Generation runs through src/lib/ai.ts; founders cannot self-trigger diligence reports.",
    warnings: ["AI output is decision support, not a guarantee — verify material claims."],
  },
  {
    id: 20,
    part: "C",
    title: "Approve a marketplace campaign for publication",
    summary: "Let a founder's raise go live in the marketplace.",
    permission: "approve_marketplace",
    keywords: ["marketplace", "campaign", "publish", "approve campaign", "go live", "deal discovery", "raise"],
    steps: [
      "Open the marketplace publication queue.",
      "Verify the company meets publication prerequisites (stage, documents, readiness).",
      "Approve to publish, or hold with required fixes.",
    ],
    reversibility: "Published campaigns can be unpublished.",
  },

  // ── Part D · Investor workflow administration ───────────────────────────────
  {
    id: 21,
    part: "D",
    title: "Approve or reject an investor profile",
    summary: "Decide whether an investor gets access to restricted features.",
    permission: "manage_investors",
    keywords: ["approve investor", "reject investor", "investor profile", "accreditation", "investor access"],
    steps: [
      "Admin → Investors, open the pending profile.",
      "Review their details and any submitted requirements.",
      "Approve or reject; approval unlocks SPV and marketplace access.",
    ],
    reversibility: "Reversible — approval can be revoked.",
  },
  {
    id: 22,
    part: "D",
    title: "Manage the investor pipeline & interest stages",
    summary: "Move investors through CRM interest stages.",
    permission: "manage_investors",
    keywords: ["pipeline", "interest", "crm", "investor crm", "stage", "interest stage", "move investor"],
    steps: [
      "Open the investor CRM / pipeline view.",
      "Update an investor's interest stage as the relationship progresses.",
      "Use timelines to track touchpoints.",
    ],
    behindScenes: "Backed by src/lib/investor-crm/.",
    reversibility: "Stages can be moved back.",
  },
  {
    id: 23,
    part: "D",
    title: "Review Partner Score & apply an override",
    summary: "Inspect an investor's Partner Score and adjust if warranted.",
    permission: "manage_investors",
    keywords: ["partner score", "score", "investor rating", "override", "tier", "coaching"],
    steps: [
      "Open the investor's Partner Score in the admin view (full score, pillars, coaching).",
      "If an override is justified, record it with a reason.",
      "Remember founders only ever see the tier and safe facts — never the numeric score, pillars, or coaching.",
    ],
    behindScenes: "Logic lives in src/lib/investor-rating/; founderFacingPartnerView enforces the founder-facing boundary.",
    warnings: ["Never expose the numeric score, pillars, or coaching to founders."],
  },

  // ── Part E · SPV operations ─────────────────────────────────────────────────
  {
    id: 24,
    part: "E",
    title: "Open an SPV",
    summary: "Start an SPV from its checklist.",
    permission: "manage_spvs",
    keywords: ["spv", "open spv", "create spv", "checklist", "special purpose vehicle"],
    steps: [
      "Admin → SPVs, create or open the SPV.",
      "Work through the checklist to move it from draft to open.",
      "Confirm prerequisites before opening for participations.",
    ],
    behindScenes: "SPV lifecycle: checklist → open → participations → requirements → closing (src/lib/spv/).",
    reversibility: "An SPV can be paused or closed.",
  },
  {
    id: 25,
    part: "E",
    title: "Manage SPV participations",
    summary: "Add and track investor participations in an open SPV.",
    permission: "manage_spvs",
    keywords: ["participation", "spv participation", "allocation", "commit", "investor participation"],
    steps: [
      "Open the SPV's participations tab.",
      "Add or update investor participations and amounts.",
      "Track status toward the SPV's target.",
    ],
    reversibility: "Participations can be edited or withdrawn before closing.",
  },
  {
    id: 26,
    part: "E",
    title: "Manage SPV investor requirements",
    summary: "Track the documents each participating investor must supply.",
    permission: "manage_spvs",
    keywords: ["requirements", "spv requirements", "investor documents", "kyc", "supporting documents"],
    steps: [
      "Open the SPV's requirements tab.",
      "Review each investor's outstanding document requirements.",
      "Mark items received or request missing ones.",
    ],
    reversibility: "Requirement status can be updated as documents arrive.",
  },
  {
    id: 27,
    part: "E",
    title: "Close an SPV",
    summary: "Finalize an SPV once participations and requirements are complete.",
    permission: "manage_spvs",
    keywords: ["close spv", "finalize spv", "closing", "complete spv", "wind down"],
    steps: [
      "Confirm all participations and requirements are satisfied.",
      "Move the SPV to closing in the lifecycle.",
      "Complete closing steps and archive.",
    ],
    warnings: ["Closing is a significant state change — verify completeness first."],
  },

  // ── Part F · Compliance & risk ──────────────────────────────────────────────
  {
    id: 28,
    part: "F",
    title: "Run or review a compliance risk scan",
    summary: "Check entities for compliance risk signals.",
    permission: "manage_compliance",
    keywords: ["compliance", "risk", "scan", "risk scan", "screening", "flag"],
    steps: [
      "Open Admin → Compliance.",
      "Run or review the risk scan for the entity in question.",
      "Triage flagged items and record outcomes.",
    ],
    behindScenes: "Compliance scanning, event logging, and escalations live in src/lib/compliance/.",
  },
  {
    id: 29,
    part: "F",
    title: "Handle a compliance escalation",
    summary: "Work a compliance issue that has been escalated.",
    permission: "manage_compliance",
    keywords: ["escalation", "compliance escalation", "investigate", "resolve flag", "compliance issue"],
    steps: [
      "Open the escalation from the compliance queue.",
      "Investigate, document findings, and decide an action.",
      "Resolve or escalate further; the event is logged.",
    ],
    warnings: ["Follow your legal/compliance policy — when unsure, escalate rather than close."],
  },

  // ── Part G · Communications ─────────────────────────────────────────────────
  {
    id: 30,
    part: "G",
    title: "Marketing — templates & sequences",
    summary: "Create a template and build or enroll a marketing sequence.",
    permission: "manage_crm",
    keywords: ["marketing", "template", "sequence", "email sequence", "enroll", "campaign", "drip"],
    steps: [
      "Admin → Marketing hub → Templates to create or edit a template.",
      "Open Sequences, add steps, and set delays/conditions.",
      "Bulk-enroll a contact list into the sequence.",
    ],
    behindScenes: "Sequences are in src/lib/marketing/; enrollList performs idempotent bulk enrollment.",
    reversibility: "Pause a sequence to stop sends.",
  },
  {
    id: 31,
    part: "G",
    title: "Import or export CRM contacts (CSV)",
    summary: "Bring contacts in or take data out via CSV.",
    permission: "manage_imports",
    keywords: ["csv", "import", "export", "contacts", "upload contacts", "data export", "crm export"],
    steps: [
      "Admin → Imports.",
      "Upload a CSV to import, mapping columns as prompted.",
      "Or export the current data set to CSV.",
    ],
    behindScenes: "Check-size parsing handles mixed units per value (see src/lib/founder-crm/csv-import.ts).",
    warnings: ["Validate a small sample after import before relying on the data."],
  },
  {
    id: 32,
    part: "G",
    title: "Trigger notification orchestration / digest",
    summary: "Run the orchestration or digest pass on demand.",
    permission: "manage_queues",
    keywords: ["orchestration", "digest", "notifications", "run digest", "cron", "trigger digest", "reminders"],
    steps: [
      "Scheduled runs happen via Vercel Cron at 07:00 and 19:00 UTC.",
      "For a manual pass, use POST /api/admin/run-digest-pass or /api/admin/notification-orchestration.",
      "Confirm results in the orchestration execution log.",
    ],
    behindScenes: "Requires CRON_SECRET for scheduled runs; staff triggers are admin-gated.",
  },

  // ── Part H · Learning administration ────────────────────────────────────────
  {
    id: 33,
    part: "H",
    title: "Create or edit a course, lesson, or quiz",
    summary: "Manage learning content.",
    permission: "manage_learning",
    keywords: ["course", "lesson", "quiz", "learning", "module", "elearning", "create course"],
    steps: [
      "Admin → Learning.",
      "Create or edit the course, its lessons, and quizzes.",
      "Publish when ready.",
    ],
    behindScenes: "Learning domain: courses, lessons, progress, badges, quizzes, spaced repetition (src/lib/learning/).",
    reversibility: "Unpublish or edit content anytime.",
  },
  {
    id: 34,
    part: "H",
    title: "Review worksheet submissions",
    summary: "Read and respond to learner worksheet submissions.",
    permission: "manage_learning",
    keywords: ["worksheet", "submission", "review worksheet", "learner", "assignment"],
    steps: [
      "Open the lesson's worksheet submissions in the admin learning area.",
      "Review each submission and leave feedback.",
    ],
  },

  // ── Part I · Platform operations ────────────────────────────────────────────
  {
    id: 35,
    part: "I",
    title: "Apply a database migration",
    summary: "Run a SQL migration safely from staging to production.",
    permission: "manage_settings",
    keywords: ["migration", "sql", "schema", "database migration", "apply migration", "supabase migration"],
    steps: [
      "Migrations live in supabase/migrations/, applied in numeric order.",
      "Apply on staging first (SQL editor or CLI) and verify.",
      "Back up production (SOP 36), then apply the same migration to production.",
    ],
    behindScenes: "Each tier has its own Supabase project. See docs/supabase-setup.md and docs/deployment-checklist.md.",
    warnings: ["Never point local at the production Supabase project. Verify on staging before production."],
  },
  {
    id: 36,
    part: "I",
    title: "Back up / restore the database",
    summary: "Protect and recover data.",
    permission: "manage_settings",
    keywords: ["backup", "restore", "pitr", "point in time", "recover database", "snapshot"],
    steps: [
      "Use the Supabase managed daily backup / Point-in-Time Recovery on the Pro plan — no local setup needed.",
      "Before risky changes (migrations, bulk deletes), confirm a recent backup or PITR window exists.",
      "To restore, use the Supabase dashboard's backup/PITR restore for the affected tier.",
    ],
    warnings: ["The local ops:backup-db script needs DATABASE_URL; managed backup/PITR is the recommended path."],
  },
  {
    id: 37,
    part: "I",
    title: "Run cron / orchestration manually",
    summary: "Kick off scheduled jobs outside their window.",
    permission: "manage_automation",
    keywords: ["cron", "run orchestration", "scheduled job", "manual run", "trigger cron"],
    steps: [
      "Scheduled: GET /api/cron/run-orchestration at 07:00 and 19:00 UTC (needs CRON_SECRET).",
      "Manual staff triggers: POST /api/admin/run-digest-pass and /api/admin/notification-orchestration.",
      "Verify in the execution log.",
    ],
  },
  {
    id: 38,
    part: "I",
    title: "Environment config & secrets",
    summary: "Manage per-tier environment variables and secrets.",
    permission: "manage_settings",
    superAdminOnly: true,
    keywords: ["env", "environment", "secrets", "config", "variables", "api key", "service role"],
    steps: [
      "Three tiers (local, staging, production), each with its own Supabase project and env file.",
      "Required: NEXT_PUBLIC_SUPABASE_URL/ANON_KEY, NEXT_PUBLIC_APP_URL, SUPABASE_SERVICE_ROLE_KEY (non-local), CRON_SECRET (staging/prod).",
      "Optional: ANTHROPIC_API_KEY, Google Calendar/Meet vars + TOKEN_ENCRYPTION_SECRET.",
    ],
    warnings: ["SUPABASE_SERVICE_ROLE_KEY is server-only — never expose it client-side or via NEXT_PUBLIC_*."],
  },
  {
    id: 39,
    part: "I",
    title: "System health check",
    summary: "Confirm environment and platform status.",
    permission: "view_system_health",
    keywords: ["health", "system health", "status", "uptime", "diagnostics", "env status"],
    steps: [
      "Open /admin/system-health for non-secret environment status.",
      "Check integrations and recent orchestration runs.",
    ],
  },
  {
    id: 40,
    part: "I",
    title: "Integrations setup",
    summary: "Connect Google Calendar/Meet and the DocuSign foundation.",
    permission: "manage_integrations",
    keywords: ["integration", "google calendar", "meet", "docusign", "connect", "oauth"],
    steps: [
      "Admin → Integrations.",
      "For Google Calendar/Meet, configure GOOGLE_CLIENT_ID/SECRET/REDIRECT_URI and TOKEN_ENCRYPTION_SECRET.",
      "Connect and verify the integration health.",
    ],
  },

  // ── Part J · Security & incident response ───────────────────────────────────
  {
    id: 41,
    part: "J",
    title: "Secure a compromised account",
    summary: "Contain a suspected account takeover.",
    permission: "manage_users",
    keywords: ["compromised", "hacked", "takeover", "suspicious login", "secure account", "breach account"],
    steps: [
      "Deactivate the account immediately (SOP 5) to block access.",
      "Review the audit trail for unexpected actions (SOP 13).",
      "Once secured, reset access (SOP 9) and reactivate, or delete if fraudulent.",
    ],
    warnings: ["Act first (deactivate), investigate second. Escalate to a super admin if platform-wide risk is suspected."],
  },
  {
    id: 42,
    part: "J",
    title: "Security incident / breach response",
    summary: "Coordinate response to a suspected security breach.",
    permission: "manage_settings",
    superAdminOnly: true,
    keywords: ["breach", "security incident", "incident response", "data breach", "compromise", "leak"],
    steps: [
      "Contain: deactivate affected accounts and revoke exposed credentials.",
      "Rotate secrets and keys (SOP 43).",
      "Assess scope via audit logs and Sentry; document a timeline.",
      "Notify per your legal/regulatory obligations.",
    ],
    warnings: ["Follow your incident policy. Preserve evidence before remediating where possible."],
  },
  {
    id: 43,
    part: "J",
    title: "Rotate secrets & keys",
    summary: "Replace credentials that may be exposed.",
    permission: "manage_settings",
    superAdminOnly: true,
    keywords: ["rotate", "secret", "key", "api key", "credential", "service role key", "rotate keys"],
    steps: [
      "Identify the affected secret (ANTHROPIC_API_KEY, SUPABASE_SERVICE_ROLE_KEY, CRON_SECRET, TOKEN_ENCRYPTION_SECRET).",
      "Generate a new value at the source and update each tier's environment.",
      "Redeploy and verify dependent features still work.",
    ],
    warnings: ["Rotating TOKEN_ENCRYPTION_SECRET invalidates stored encrypted tokens (e.g. Google) — users must reconnect."],
  },
  {
    id: 44,
    part: "J",
    title: "Handle fraud / abuse",
    summary: "Deal with fake signups and spam.",
    permission: "manage_compliance",
    keywords: ["fraud", "abuse", "spam", "fake account", "bot", "scam", "fake signup"],
    steps: [
      "Confirm the abuse signal (pattern of signups, spammy content).",
      "Deactivate or delete the offending accounts (SOPs 5, 7).",
      "Log a compliance event and watch for recurrence.",
    ],
  },

  // ── Part K · Data & privacy ─────────────────────────────────────────────────
  {
    id: 45,
    part: "K",
    title: "Fulfil a data access / export request",
    summary: "Provide a user a copy of their data (portability).",
    permission: "manage_compliance",
    keywords: ["data access", "export request", "portability", "dsar", "subject access", "my data", "gdpr export"],
    steps: [
      "Verify the requester's identity.",
      "Collect their profile and owned records (company, documents metadata, interests).",
      "Provide the export through an approved channel and log the fulfilment.",
    ],
    warnings: ["Share only the requester's own data; never include other users' personal information."],
  },
  {
    id: 46,
    part: "K",
    title: "Data rectification request",
    summary: "Correct inaccurate personal data on request.",
    permission: "manage_users",
    keywords: ["rectification", "correct data", "update data", "fix profile", "amend", "wrong data"],
    steps: [
      "Verify the request and the correct values.",
      "Update the relevant profile fields (SOP 4).",
      "Confirm the correction back to the requester.",
    ],
  },
  {
    id: 47,
    part: "K",
    title: "Data retention & scheduled deletion",
    summary: "Apply the retention policy for old or inactive data.",
    permission: "manage_compliance",
    keywords: ["retention", "data retention", "scheduled deletion", "purge old", "policy", "erasure schedule"],
    steps: [
      "Identify records past their retention window per policy.",
      "Deactivate or delete per the policy (SOPs 5, 7), backing up first if required.",
      "Record what was removed and when.",
    ],
    warnings: ["Deletion here is irreversible — confirm the retention rule and a backup before purging."],
  },

  // ── Part L · Staff governance ───────────────────────────────────────────────
  {
    id: 48,
    part: "L",
    title: "Onboard a new admin / analyst",
    summary: "Provision a new internal team member.",
    permission: "assign_roles",
    keywords: ["onboard admin", "new staff", "provision", "new team member", "staff onboarding", "grant access"],
    steps: [
      "Invite them as staff (SOP 3) with the appropriate workspace role.",
      "Assign the right RBAC role/permissions (SOP 11) — least privilege.",
      "Share this operations manual and any team-specific runbooks.",
    ],
  },
  {
    id: 49,
    part: "L",
    title: "Offboard a staff member",
    summary: "Cleanly remove a departing team member's access.",
    permission: "assign_roles",
    keywords: ["offboard", "remove staff", "departing", "revoke admin", "leaver", "deprovision"],
    steps: [
      "Deactivate their account immediately (SOP 5) to revoke access.",
      "Reassign or archive anything they owned that must continue.",
      "Remove RBAC roles/overrides; delete the account only if required by policy.",
    ],
    warnings: ["You cannot deactivate or delete the last active admin — appoint a replacement first."],
  },
  {
    id: 50,
    part: "L",
    title: "Periodic access review",
    summary: "Regularly confirm who holds elevated access.",
    permission: "assign_roles",
    keywords: ["access review", "audit access", "who has admin", "review permissions", "least privilege", "quarterly review"],
    steps: [
      "List current admins, analysts, and super admins (User management + User Permissions).",
      "Confirm each still needs their level; downgrade or offboard where not.",
      "Record the review date and outcome.",
    ],
  },
  {
    id: 51,
    part: "L",
    title: "Break-glass / emergency super-admin access",
    summary: "Grant temporary elevated access during an emergency.",
    permission: "assign_roles",
    superAdminOnly: true,
    keywords: ["break glass", "emergency access", "elevate", "temporary admin", "super admin access", "emergency"],
    steps: [
      "Confirm the emergency justifies elevation and who authorizes it.",
      "Grant the minimal elevated role/permissions needed, time-boxed.",
      "Revoke immediately after the incident and record it in the access review.",
    ],
    warnings: ["Elevation must be temporary and logged. Never leave break-glass access in place."],
  },
  {
    id: 52,
    part: "L",
    title: "Escalation matrix — who approves what",
    summary: "Reference for routing decisions to the right approver.",
    permission: null,
    keywords: ["escalation", "who approves", "approver", "matrix", "routing", "decision", "escalate to"],
    steps: [
      "User deletion, role changes: a holder of manage_users / assign_roles (often super admin).",
      "Billing/plan changes: manage_billing.",
      "Compliance and security incidents: manage_compliance / super admin.",
      "When unsure, route up — never guess on irreversible actions.",
    ],
  },

  // ── Part M · Release & deployment ───────────────────────────────────────────
  {
    id: 53,
    part: "M",
    title: "Deploy staging → production",
    summary: "Ship a release safely.",
    permission: "manage_settings",
    keywords: ["deploy", "release", "ship", "production", "staging", "build", "deployment"],
    steps: [
      "Build and verify on staging (npm run build:staging) and run tests.",
      "Apply any pending migrations to staging and verify (SOP 35).",
      "Promote to production (npm run build:production) following docs/deployment-checklist.md.",
    ],
    warnings: ["Never deploy a release whose migrations haven't been verified on staging."],
  },
  {
    id: 54,
    part: "M",
    title: "Roll back a release",
    summary: "Recover from a bad deploy.",
    permission: "manage_settings",
    keywords: ["rollback", "revert", "bad deploy", "roll back", "undo release", "previous version"],
    steps: [
      "Redeploy the previous known-good build.",
      "If a migration caused the issue, assess whether a down-migration or a backup restore (SOP 36) is needed.",
      "Confirm health (SOP 39) and document the incident.",
    ],
    warnings: ["Schema rollbacks are risky — prefer forward fixes; restore from backup only as a last resort."],
  },

  // ── Part N · Trust, safety & support ────────────────────────────────────────
  {
    id: 55,
    part: "N",
    title: "Respond to a support / live-agent handoff",
    summary: "Pick up a request escalated from the assistant to a human.",
    permission: "manage_beta_operations",
    keywords: ["support", "live agent", "handoff", "help request", "escalated chat", "human support"],
    steps: [
      "Open the live-agent request queue (assistant handoffs).",
      "Review the user's context and respond through the appropriate channel.",
      "Close the request and capture any follow-up actions.",
    ],
    behindScenes: "Handoffs come through the assistant's live-agent-request route.",
  },
  {
    id: 56,
    part: "N",
    title: "Moderate content",
    summary: "Review and act on reported or risky content.",
    permission: "manage_compliance",
    keywords: ["moderate", "content", "report", "deal room", "message", "listing", "remove content"],
    steps: [
      "Open the reported content (deal room, message, or marketplace listing).",
      "Assess against policy.",
      "Remove or hide offending content and note the action.",
    ],
  },
  {
    id: 57,
    part: "N",
    title: "Email deliverability & unsubscribe handling",
    summary: "Keep marketing email compliant and deliverable.",
    permission: "manage_crm",
    keywords: ["email", "deliverability", "unsubscribe", "bounce", "spam complaint", "suppression", "opt out"],
    steps: [
      "Honor unsubscribe requests — suppressed contacts must not receive further sends.",
      "Monitor bounces and complaints; remove hard-bouncing addresses.",
      "Sequences skip unsubscribed contacts automatically; verify suppression is working.",
    ],
    warnings: ["Sending to people who opted out is a compliance violation — never override a suppression."],
  },

  // ── Part O · Calendar, scheduling & email ───────────────────────────────────
  {
    id: 58,
    part: "O",
    title: "Connect your Google account (Calendar, Meet, Gmail)",
    summary: "Link Google so events sync and meetings get Google Meet links.",
    permission: null,
    keywords: ["google", "connect", "oauth", "calendar", "meet", "gmail", "integration", "link account"],
    steps: [
      "Go to Admin → Integrations and click Connect Google.",
      "Approve the requested Calendar and Gmail scopes.",
      "Once connected, calendar events sync to Google and 'Add Google Meet' generates a Meet link.",
    ],
    behindScenes: "Uses OAuth with encrypted token storage; the app refreshes the access token automatically. Without a connection, events still work locally — they just don't sync or get Meet links.",
    reversibility: "Disconnect anytime from Integrations.",
    warnings: ["Requires GOOGLE_CLIENT_ID/SECRET/REDIRECT_URI + TOKEN_ENCRYPTION_SECRET to be configured for the tier."],
  },
  {
    id: 59,
    part: "O",
    title: "Schedule & manage calendar events",
    summary: "Create, edit, and cancel events from the in-app calendar.",
    permission: null,
    keywords: ["calendar", "event", "meeting", "schedule", "create event", "agenda", "month view"],
    steps: [
      "Open Calendar (founder/investor/admin workspaces all have it).",
      "Click a day or New event to create; toggle 'Add Google Meet' for a video link.",
      "Switch Month/Agenda with the toggle; click any event to edit or delete it.",
    ],
    behindScenes: "Events are stored in calendar_events (your authoritative copy) and synced to Google when connected.",
    reversibility: "Edit or delete events anytime; deletes also remove the synced Google event.",
  },
  {
    id: 60,
    part: "O",
    title: "Share availability & take bookings",
    summary: "Let people book open time slots that land on your calendar.",
    permission: null,
    keywords: ["availability", "booking", "schedule", "slots", "calendly", "book a meeting", "scheduling link"],
    steps: [
      "Open Scheduling, set your weekly hours, slot length, and buffer, then Save.",
      "Share your booking link (/schedule/<your-id>).",
      "Bookers pick an open slot and confirm; it creates the meeting with a Meet link and emails both sides.",
    ],
    behindScenes: "Open slots = your hours minus Google free/busy and existing events. Bookings re-validate the slot before confirming.",
  },
  {
    id: 61,
    part: "O",
    title: "Use the platform email inbox",
    summary: "Send, reply to, search, and manage email from inside the platform.",
    permission: null,
    keywords: ["inbox", "email", "compose", "reply", "send mail", "conversation", "thread"],
    steps: [
      "Open Inbox (all three workspaces). Compose to start a conversation; replies thread automatically.",
      "Search filters by contact or subject; the nav badge shows unread count.",
      "Open a conversation to reply, or delete it from the reading pane.",
    ],
    behindScenes: "Outbound sends via Resend with a reply+<token> address; inbound replies route back to the thread via the webhook. Your name shows in the From line.",
    warnings: ["This is the platform mailbox, not your personal Gmail. Founder→investor emails stay mediated — never expose investor emails to founders."],
  },
  {
    id: 62,
    part: "O",
    title: "Configure inbound email for the inbox",
    summary: "Wire a provider so replies flow back into the inbox.",
    permission: "manage_integrations",
    keywords: ["inbound", "webhook", "mx", "resend inbound", "reply routing", "email setup", "receive email"],
    steps: [
      "Set INBOUND_EMAIL_DOMAIN and INBOUND_WEBHOOK_SECRET for the tier.",
      "Add an MX record for the inbound domain at your provider (Resend Inbound / SendGrid / Mailgun).",
      "Point the provider's inbound webhook at /api/email/inbound?key=<INBOUND_WEBHOOK_SECRET>.",
      "Test: send from the inbox, reply to it, confirm the reply appears in the thread.",
    ],
    warnings: ["Without the webhook configured, sending works but replies won't appear in the inbox."],
  },
  {
    id: 63,
    part: "O",
    title: "Deploy & verify the calendar + inbox features",
    summary: "Roll out and smoke-test calendar, scheduler, and inbox on a tier.",
    permission: "manage_settings",
    keywords: ["deploy", "verify", "smoke test", "rollout", "calendar", "inbox", "migrations"],
    steps: [
      "Apply migrations 20260620002–20260620005 (staging first).",
      "Set Google, Resend, inbound, and CRON_SECRET env vars in Vercel and redeploy.",
      "Register the Google redirect URI; point the inbound provider at /api/email/inbound.",
      "Run the smoke test in docs/deploy-verify-calendar-email.md, then repeat for production.",
    ],
    behindScenes: "Full step-by-step and troubleshooting live in docs/deploy-verify-calendar-email.md.",
    warnings: ["Pages 500 until the migrations are applied for that tier; email is silent until Resend is configured."],
  },
  {
    id: 64,
    part: "I",
    title: "Run the day from the Daily Operating Console",
    summary: "Use /admin/playbook — the self-syncing operating playbook — to work each day in order.",
    permission: "view_admin_dashboard",
    keywords: ["playbook", "daily console", "operating console", "daily operations", "runbook", "operating loop", "where do i start", "morning routine", "ops console"],
    steps: [
      "Open Admin → Operation → Daily Console (/admin/playbook).",
      "Clear any drift warning at the top: undocumented surfaces show as empty cards to fill in; orphaned entries (from removed menu items) are listed under 'Needs cleanup'.",
      "Work the blocks in order — Open the day, Core operations, then Close the day — following each card's steps.",
      "Watch the live 'pending' badges (investors awaiting accreditation, intro requests, event applications) and clear them at their surface.",
      "Admins can edit any card's steps, cadence, gates, and role note inline — content lives in the database, so updating the playbook never needs a deploy.",
    ],
    behindScenes:
      "The console reads the SAME admin nav registry the sidebar renders from and joins editable content from the playbook_module / _step / _flag tables. Because the module list is never duplicated, adding, renaming, or removing a menu item flows through automatically or lights up as drift — the menu is the doc.",
    reversibility: "Editing a card is non-destructive and immediate; there is no publish step. Removing steps just clears them.",
    warnings: ["Hard-gate flags (amber) are operating rules, e.g. 'no restricted investor access until kyc_status = verified' — do not treat them as optional."],
  },
  {
    id: 65,
    part: "G",
    title: "Run the marketing daily operating loop",
    summary: "The Open → Core → Close marketing loop across the hub's real surfaces.",
    permission: "view_admin_dashboard",
    keywords: ["marketing", "marketing console", "daily loop", "marketing operations", "campaigns", "daily marketing", "marketing routine", "open core close", "marketing daily", "operator loop"],
    steps: [
      "Open — Dashboard: review the engagement funnel and integration health at Marketing hub → Dashboard (/admin/marketing).",
      "Open — Action review: clear staged and scheduled campaigns and any bounce or webhook alerts (/admin/marketing/campaigns; platform queue at /admin/actions).",
      "Open — Replies: work unhandled replies in the inbox (/admin/inbox) and CRM messages (/admin/crm/messages). Route interested → follow-up, unsubscribe → suppression, and anything mentioning guarantees or placement → securities counsel (do not answer directly).",
      "Core — Lead pipeline: leads live in Odoo (the external system of record). Review the mirrored contacts and list hygiene before any send (/admin/marketing/contacts, /admin/marketing/lists). Do not schedule a segment until its import is clean.",
      "Core — Email campaigns: build and QA the campaign, split large sends into thirds, and send only after compliance review is approved (/admin/marketing/campaigns, sequences at /admin/marketing/sequences).",
      "Core — Phone follow-up: call only non-suppressed leads; cap at two attempts per lead, then close. Log via CRM outreach (/admin/crm/outreach).",
      "Core — Content and assets: keep templates and pillar content fresh — review anything older than ~30 days (/admin/marketing/templates and the AEO pages at /admin/marketing/aeo).",
      "Core — Brand consistency: keep to the approved navy → royal-blue palette. Deprecated hexes (#0D9488, #5EEAD4, #534AB7 / #3C3489) are flagged by CI — fix the flagged files.",
      "Core — AI CMO advisory: read the AI CMO's recommendations (Marketing hub → Plan, /admin/marketing/plan, and the AI CMO copilot) and act on them manually. The advisory is read-only.",
      "Core — SEO / AEO: check answer-engine visibility and publish or refresh citable pages at /admin/marketing/aeo; turn gaps into content tasks.",
      "Close — End of day: review today's engagement rollup (/admin/marketing/analytics), stage tomorrow's batches, note open blockers, and write a one-line log.",
    ],
    behindScenes:
      "Odoo is the external system of record for leads; Supabase carries a read mirror plus the console's own action state. Engagement metrics come from marketing_events (send / open / click / reply / signup) — there is deliberately no funding or outcome data to report. The AI CMO reads analytics only and never writes operational tables. The playbook (/admin/playbook) documents the steps; the Marketing hub surfaces are where they are performed.",
    reversibility: "Most steps are review or queue actions; a scheduled campaign can be paused or cancelled before it sends.",
    warnings: [
      "Never schedule a send on a segment whose import is not clean.",
      "Never send a campaign that has not passed compliance review.",
    ],
  },
  {
    id: 66,
    part: "F",
    title: "Marketing compliance gates",
    summary: "The load-bearing rules that keep outbound marketing in the engagement register and out of securities-offer territory.",
    permission: "manage_compliance",
    keywords: ["marketing compliance", "engagement register", "copy review", "two attempt cap", "2 attempt", "suppress on convert", "suppression", "reg cf", "securities counsel", "outcome language", "guarantees", "placement"],
    steps: [
      "Engagement, not outcome: marketing reporting aggregates engagement only (sends, opens, clicks, replies, signups). Never record or promise a fundraising outcome or a guaranteed result — the data model does not store one.",
      "Copy-review gate: a campaign must pass compliance review before it can send. An unreviewed or rejected campaign is blocked — the send control is disabled and the send action is refused.",
      "Two-attempt phone cap: call each lead at most twice, then close the task. The cap is enforced, not advisory.",
      "Suppress-on-convert: when a lead signs up they are added to the suppression list automatically. Suppressed and unsubscribed contacts are excluded from every send and call queue.",
      "Reg CF intermediary tension: any reply mentioning guarantees or placement is routed to securities counsel for review before any external commitment. Do not respond to those directly.",
    ],
    behindScenes:
      "These are enforced in schema and route logic, not just UI copy: engagement-only tables (no outcome columns), a send handler that hard-checks compliance approval, a database cap on call attempts, and recipient queries that exclude the suppression list.",
    reversibility: "The gates are preventive — they block a non-compliant action rather than something to undo. A campaign can be revised and re-reviewed.",
    warnings: [
      "These are enforcement rules, not style guidance — do not work around them.",
      "'Educational community content only — not an offer of securities' applies to all outbound marketing.",
    ],
  },
];

/** Lookup an SOP by id. */
export function getSopById(id: number): SopEntry | undefined {
  return ADMIN_SOPS.find((s) => s.id === id);
}
