-- Auto-generated by scripts/build-emails.mjs — do not edit by hand.
-- Re-run `npm run build:emails` to regenerate. Idempotent via on conflict (name).

insert into public.email_template_masters (name, description, mjml_source, compiled_html, placeholder_schema)
values
  ('Announcement', 'Gradient banner, single column, one call to action.', '<mjml>
  <mj-head>
    <mj-attributes>
      <mj-all font-family="Helvetica, Arial, sans-serif" />
      <mj-text color="#16223F" font-size="15px" line-height="1.6" />
    </mj-attributes>
    <mj-preview>{{headline}}</mj-preview>
  </mj-head>
  <mj-body background-color="#F6F8FC">
    <!-- Gradient banner (locked brand layer). The {{banner_image}} slot lets the
         editor swap to an image banner; a navy overlay is applied at render time. -->
    <mj-section background-color="#0A1A40" background-url="{{banner_image}}" background-size="cover" background-position="center" padding="40px 24px">
      <mj-column>
        <mj-image src="{{logo}}" width="132px" align="left" padding="0 0 16px 0" />
        <mj-text color="#FFFFFF" font-size="26px" font-weight="bold" line-height="1.25">{{headline}}</mj-text>
      </mj-column>
    </mj-section>

    <mj-section background-color="#FFFFFF" padding="28px 24px 8px">
      <mj-column>
        <mj-text>{{body}}</mj-text>
      </mj-column>
    </mj-section>

    <mj-section background-color="#FFFFFF" padding="8px 24px 32px">
      <mj-column>
        <mj-button href="{{cta_url}}" background-color="#1A6CE4" color="#FFFFFF" font-weight="bold" font-size="15px" border-radius="8px" align="left" padding="0">{{cta_text}}</mj-button>
      </mj-column>
    </mj-section>

    <!-- Mandatory footer (locked). {{unsubscribe_url}} is merged per-recipient. -->
    <mj-section background-color="#F6F8FC" padding="8px 24px 24px">
      <mj-column>
        <mj-text align="center" color="#5A6B8C" font-size="12px" line-height="1.6">
          iCFO Capital Global, Inc. · La Jolla, CA 92037<br />
          <a href="{{unsubscribe_url}}" style="color:#5A6B8C;">Unsubscribe</a> ·
          <a href="{{view_in_browser_url}}" style="color:#5A6B8C;">View in browser</a><br />
          You''re receiving this because you opted in with iCFO Capital Global, Inc.
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
', '<!doctype html>
<html lang="und" dir="auto" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
  <head>
    <title></title>
    <!--[if !mso]><!-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--<![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
      #outlook a { padding:0; }
      body { margin:0;padding:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%; }
      table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt; }
      img { border:0;height:auto;line-height:100%; outline:none;text-decoration:none;-ms-interpolation-mode:bicubic; }
      p { display:block;margin:13px 0; }
    </style>
    <!--[if mso]>
    <noscript>
    <xml>
    <o:OfficeDocumentSettings>
      <o:AllowPNG/>
      <o:PixelsPerInch>96</o:PixelsPerInch>
    </o:OfficeDocumentSettings>
    </xml>
    </noscript>
    <![endif]-->
    <!--[if lte mso 11]>
    <style type="text/css">
      .mj-outlook-group-fix { width:100% !important; }
    </style>
    <![endif]-->
    
    
    <style type="text/css">
      @media only screen and (min-width:480px) {
        .mj-column-per-100 { width:100% !important; max-width: 100%; }
      }
    </style>
    <style media="screen and (min-width:480px)">
      .moz-text-html .mj-column-per-100 { width:100% !important; max-width: 100%; }
    </style>
    
    
  
    
    <style type="text/css">

    @media only screen and (max-width:479px) {
      table.mj-full-width-mobile { width: 100% !important; }
      td.mj-full-width-mobile { width: auto !important; }
    }
  
    </style>
    
    
  </head>
  
      <body  style="word-spacing:normal;background-color:#F6F8FC;">
        
    <div style="display:none;font-size:1px;color:#ffffff;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;">{{headline}}</div>
  
        <div
           aria-roledescription="email" role="article" lang="und" dir="auto" style="word-spacing:normal;background-color:#F6F8FC;"
        >
        <!-- Gradient banner (locked brand layer). The {{banner_image}} slot lets the
         editor swap to an image banner; a navy overlay is applied at render time. -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#0A1A40" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><v:rect style="width:600px;" xmlns:v="urn:schemas-microsoft-com:vml" fill="true" stroke="false"><v:fill origin="0.5, 0.5" position="0.5, 0.5" src="{{banner_image}}" color="#0A1A40" type="tile" size="1,1" aspect="atleast" /><v:textbox style="mso-fit-shape-to-text:true" inset="0,0,0,0"><![endif]-->
          
      <div  style="background:#0A1A40 url(''{{banner_image}}'') center center / cover repeat;background-position:center center;background-repeat:repeat;background-size:cover;margin:0px auto;max-width:600px;">
        <div  style="line-height:0;font-size:0;">
        <table
           align="center" background="{{banner_image}}" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#0A1A40 url(''{{banner_image}}'') center center / cover repeat;background-position:center center;background-repeat:repeat;background-size:cover;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:40px 24px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0 0 16px 0;word-break:break-word;"
                >
                  
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;"
      >
        <tbody>
          <tr>
            <td  style="width:132px;">
              
      <img
         alt="" src="https://icapos.com/email-logo.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;" width="132" height="auto"
      />
    
            </td>
          </tr>
        </tbody>
      </table>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:26px;font-weight:bold;line-height:1.25;text-align:left;color:#FFFFFF;"
      >{{headline}}</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        </div>
      </div>
    
        <!--[if mso | IE]></v:textbox></v:rect></td></tr></table><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#FFFFFF" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#FFFFFF;background-color:#FFFFFF;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#FFFFFF;background-color:#FFFFFF;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:28px 24px 8px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:15px;line-height:1.6;text-align:left;color:#16223F;"
      >{{body}}</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#FFFFFF" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#FFFFFF;background-color:#FFFFFF;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#FFFFFF;background-color:#FFFFFF;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:8px 24px 32px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0;word-break:break-word;"
                >
                  
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:separate;line-height:100%;"
      >
        <tbody>
          <tr>
            <td
               align="center" bgcolor="#1A6CE4" role="presentation" style="border:none;border-radius:8px;cursor:auto;mso-padding-alt:10px 25px;background:#1A6CE4;" valign="middle"
            >
              <a
                 href="{{cta_url}}" style="display:inline-block;background:#1A6CE4;color:#FFFFFF;font-family:Helvetica, Arial, sans-serif;font-size:15px;font-weight:bold;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;border-radius:8px;" target="_blank"
              >
                {{cta_text}}
              </a>
            </td>
          </tr>
        </tbody>
      </table>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    <!-- Mandatory footer (locked). {{unsubscribe_url}} is merged per-recipient. -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#F6F8FC" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#F6F8FC;background-color:#F6F8FC;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#F6F8FC;background-color:#F6F8FC;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:8px 24px 24px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:12px;line-height:1.6;text-align:center;color:#5A6B8C;"
      >iCFO Capital Global, Inc. · La Jolla, CA 92037<br />
          <a href="{{unsubscribe_url}}" style="color:#5A6B8C;">Unsubscribe</a> ·
          <a href="{{view_in_browser_url}}" style="color:#5A6B8C;">View in browser</a><br />
          You''re receiving this because you opted in with iCFO Capital Global, Inc.</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    
      </div>
      </body>
    
</html>
  ', '{"slots":[{"key":"headline","type":"text","label":"Headline","max_length":90,"required":true},{"key":"body","type":"textarea","label":"Body copy","required":true},{"key":"cta_text","type":"text","label":"CTA text","max_length":30,"required":true},{"key":"cta_url","type":"url","label":"CTA link","required":true},{"key":"banner_image","type":"image","label":"Banner image","editable":true,"required":false}],"locked":["logo","brand_colors","footer_legal","unsubscribe"]}'::jsonb),
  ('Newsletter', 'Image banner with two-column content sections.', '<mjml>
  <mj-head>
    <mj-attributes>
      <mj-all font-family="Helvetica, Arial, sans-serif" />
      <mj-text color="#16223F" font-size="15px" line-height="1.6" />
    </mj-attributes>
    <mj-preview>{{headline}}</mj-preview>
  </mj-head>
  <mj-body background-color="#F6F8FC">
    <!-- Image banner with navy overlay for contrast (locked brand layer). -->
    <mj-section background-color="#0A1A40" background-url="{{banner_image}}" background-size="cover" background-position="center" padding="44px 24px">
      <mj-column>
        <mj-image src="{{logo}}" width="132px" align="left" padding="0 0 14px 0" />
        <mj-text color="#FFFFFF" font-size="24px" font-weight="bold" line-height="1.25">{{headline}}</mj-text>
      </mj-column>
    </mj-section>

    <mj-section background-color="#FFFFFF" padding="26px 24px 6px">
      <mj-column>
        <mj-text>{{intro}}</mj-text>
      </mj-column>
    </mj-section>

    <!-- Two-column section. -->
    <mj-section background-color="#FFFFFF" padding="8px 24px">
      <mj-column>
        <mj-text font-size="17px" font-weight="bold" color="#0A1A40">{{section_one_title}}</mj-text>
        <mj-text>{{section_one_body}}</mj-text>
      </mj-column>
      <mj-column>
        <mj-text font-size="17px" font-weight="bold" color="#0A1A40">{{section_two_title}}</mj-text>
        <mj-text>{{section_two_body}}</mj-text>
      </mj-column>
    </mj-section>

    <mj-section background-color="#FFFFFF" padding="14px 24px 32px">
      <mj-column>
        <mj-button href="{{cta_url}}" background-color="#1A6CE4" color="#FFFFFF" font-weight="bold" font-size="15px" border-radius="8px" padding="0">{{cta_text}}</mj-button>
      </mj-column>
    </mj-section>

    <mj-section background-color="#F6F8FC" padding="8px 24px 24px">
      <mj-column>
        <mj-text align="center" color="#5A6B8C" font-size="12px" line-height="1.6">
          iCFO Capital Global, Inc. · La Jolla, CA 92037<br />
          <a href="{{unsubscribe_url}}" style="color:#5A6B8C;">Unsubscribe</a> ·
          <a href="{{view_in_browser_url}}" style="color:#5A6B8C;">View in browser</a><br />
          You''re receiving this because you opted in with iCFO Capital Global, Inc.
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
', '<!doctype html>
<html lang="und" dir="auto" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
  <head>
    <title></title>
    <!--[if !mso]><!-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--<![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
      #outlook a { padding:0; }
      body { margin:0;padding:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%; }
      table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt; }
      img { border:0;height:auto;line-height:100%; outline:none;text-decoration:none;-ms-interpolation-mode:bicubic; }
      p { display:block;margin:13px 0; }
    </style>
    <!--[if mso]>
    <noscript>
    <xml>
    <o:OfficeDocumentSettings>
      <o:AllowPNG/>
      <o:PixelsPerInch>96</o:PixelsPerInch>
    </o:OfficeDocumentSettings>
    </xml>
    </noscript>
    <![endif]-->
    <!--[if lte mso 11]>
    <style type="text/css">
      .mj-outlook-group-fix { width:100% !important; }
    </style>
    <![endif]-->
    
    
    <style type="text/css">
      @media only screen and (min-width:480px) {
        .mj-column-per-100 { width:100% !important; max-width: 100%; }
.mj-column-per-50 { width:50% !important; max-width: 50%; }
      }
    </style>
    <style media="screen and (min-width:480px)">
      .moz-text-html .mj-column-per-100 { width:100% !important; max-width: 100%; }
.moz-text-html .mj-column-per-50 { width:50% !important; max-width: 50%; }
    </style>
    
    
  
    
    <style type="text/css">

    @media only screen and (max-width:479px) {
      table.mj-full-width-mobile { width: 100% !important; }
      td.mj-full-width-mobile { width: auto !important; }
    }
  
    </style>
    
    
  </head>
  
      <body  style="word-spacing:normal;background-color:#F6F8FC;">
        
    <div style="display:none;font-size:1px;color:#ffffff;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;">{{headline}}</div>
  
        <div
           aria-roledescription="email" role="article" lang="und" dir="auto" style="word-spacing:normal;background-color:#F6F8FC;"
        >
        <!-- Image banner with navy overlay for contrast (locked brand layer). -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#0A1A40" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><v:rect style="width:600px;" xmlns:v="urn:schemas-microsoft-com:vml" fill="true" stroke="false"><v:fill origin="0.5, 0.5" position="0.5, 0.5" src="{{banner_image}}" color="#0A1A40" type="tile" size="1,1" aspect="atleast" /><v:textbox style="mso-fit-shape-to-text:true" inset="0,0,0,0"><![endif]-->
          
      <div  style="background:#0A1A40 url(''{{banner_image}}'') center center / cover repeat;background-position:center center;background-repeat:repeat;background-size:cover;margin:0px auto;max-width:600px;">
        <div  style="line-height:0;font-size:0;">
        <table
           align="center" background="{{banner_image}}" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#0A1A40 url(''{{banner_image}}'') center center / cover repeat;background-position:center center;background-repeat:repeat;background-size:cover;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:44px 24px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0 0 14px 0;word-break:break-word;"
                >
                  
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;"
      >
        <tbody>
          <tr>
            <td  style="width:132px;">
              
      <img
         alt="" src="https://icapos.com/email-logo.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;" width="132" height="auto"
      />
    
            </td>
          </tr>
        </tbody>
      </table>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:24px;font-weight:bold;line-height:1.25;text-align:left;color:#FFFFFF;"
      >{{headline}}</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        </div>
      </div>
    
        <!--[if mso | IE]></v:textbox></v:rect></td></tr></table><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#FFFFFF" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#FFFFFF;background-color:#FFFFFF;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#FFFFFF;background-color:#FFFFFF;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:26px 24px 6px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:15px;line-height:1.6;text-align:left;color:#16223F;"
      >{{intro}}</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    <!-- Two-column section. -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#FFFFFF" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#FFFFFF;background-color:#FFFFFF;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#FFFFFF;background-color:#FFFFFF;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:8px 24px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:276px;" ><![endif]-->
            
      <div
         class="mj-column-per-50 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:17px;font-weight:bold;line-height:1.6;text-align:left;color:#0A1A40;"
      >{{section_one_title}}</div>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:15px;line-height:1.6;text-align:left;color:#16223F;"
      >{{section_one_body}}</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td><td class="" style="vertical-align:top;width:276px;" ><![endif]-->
            
      <div
         class="mj-column-per-50 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:17px;font-weight:bold;line-height:1.6;text-align:left;color:#0A1A40;"
      >{{section_two_title}}</div>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:15px;line-height:1.6;text-align:left;color:#16223F;"
      >{{section_two_body}}</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#FFFFFF" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#FFFFFF;background-color:#FFFFFF;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#FFFFFF;background-color:#FFFFFF;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:14px 24px 32px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="center" style="font-size:0px;padding:0;word-break:break-word;"
                >
                  
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:separate;line-height:100%;"
      >
        <tbody>
          <tr>
            <td
               align="center" bgcolor="#1A6CE4" role="presentation" style="border:none;border-radius:8px;cursor:auto;mso-padding-alt:10px 25px;background:#1A6CE4;" valign="middle"
            >
              <a
                 href="{{cta_url}}" style="display:inline-block;background:#1A6CE4;color:#FFFFFF;font-family:Helvetica, Arial, sans-serif;font-size:15px;font-weight:bold;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;border-radius:8px;" target="_blank"
              >
                {{cta_text}}
              </a>
            </td>
          </tr>
        </tbody>
      </table>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#F6F8FC" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#F6F8FC;background-color:#F6F8FC;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#F6F8FC;background-color:#F6F8FC;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:8px 24px 24px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:12px;line-height:1.6;text-align:center;color:#5A6B8C;"
      >iCFO Capital Global, Inc. · La Jolla, CA 92037<br />
          <a href="{{unsubscribe_url}}" style="color:#5A6B8C;">Unsubscribe</a> ·
          <a href="{{view_in_browser_url}}" style="color:#5A6B8C;">View in browser</a><br />
          You''re receiving this because you opted in with iCFO Capital Global, Inc.</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    
      </div>
      </body>
    
</html>
  ', '{"slots":[{"key":"headline","type":"text","label":"Headline","max_length":90,"required":true},{"key":"intro","type":"textarea","label":"Intro paragraph","required":true},{"key":"section_one_title","type":"text","label":"Section 1 title","max_length":60,"required":true},{"key":"section_one_body","type":"textarea","label":"Section 1 body","required":true},{"key":"section_two_title","type":"text","label":"Section 2 title","max_length":60,"required":true},{"key":"section_two_body","type":"textarea","label":"Section 2 body","required":true},{"key":"cta_text","type":"text","label":"CTA text","max_length":30,"required":true},{"key":"cta_url","type":"url","label":"CTA link","required":true},{"key":"banner_image","type":"image","label":"Banner image","editable":true,"required":false}],"locked":["logo","brand_colors","footer_legal","unsubscribe"]}'::jsonb),
  ('Promo', 'Centered gradient banner, short copy, large call to action.', '<mjml>
  <mj-head>
    <mj-attributes>
      <mj-all font-family="Helvetica, Arial, sans-serif" />
      <mj-text color="#16223F" font-size="15px" line-height="1.6" />
    </mj-attributes>
    <mj-preview>{{headline}}</mj-preview>
  </mj-head>
  <mj-body background-color="#F6F8FC">
    <!-- Centered gradient banner (locked brand layer). -->
    <mj-section background-color="#0A1A40" background-url="{{banner_image}}" background-size="cover" background-position="center" padding="48px 24px" text-align="center">
      <mj-column>
        <mj-image src="{{logo}}" width="140px" align="center" padding="0 0 18px 0" />
        <mj-text align="center" color="#FFFFFF" font-size="28px" font-weight="bold" line-height="1.2">{{headline}}</mj-text>
        <mj-text align="center" color="#C9D8F5" font-size="16px" line-height="1.5" padding-top="8px">{{subhead}}</mj-text>
      </mj-column>
    </mj-section>

    <mj-section background-color="#FFFFFF" padding="32px 24px" text-align="center">
      <mj-column>
        <mj-button href="{{cta_url}}" background-color="#1A6CE4" color="#FFFFFF" font-weight="bold" font-size="17px" border-radius="10px" inner-padding="16px 32px" align="center">{{cta_text}}</mj-button>
      </mj-column>
    </mj-section>

    <mj-section background-color="#F6F8FC" padding="8px 24px 24px">
      <mj-column>
        <mj-text align="center" color="#5A6B8C" font-size="12px" line-height="1.6">
          iCFO Capital Global, Inc. · La Jolla, CA 92037<br />
          <a href="{{unsubscribe_url}}" style="color:#5A6B8C;">Unsubscribe</a> ·
          <a href="{{view_in_browser_url}}" style="color:#5A6B8C;">View in browser</a><br />
          You''re receiving this because you opted in with iCFO Capital Global, Inc.
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
', '<!doctype html>
<html lang="und" dir="auto" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
  <head>
    <title></title>
    <!--[if !mso]><!-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--<![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
      #outlook a { padding:0; }
      body { margin:0;padding:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%; }
      table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt; }
      img { border:0;height:auto;line-height:100%; outline:none;text-decoration:none;-ms-interpolation-mode:bicubic; }
      p { display:block;margin:13px 0; }
    </style>
    <!--[if mso]>
    <noscript>
    <xml>
    <o:OfficeDocumentSettings>
      <o:AllowPNG/>
      <o:PixelsPerInch>96</o:PixelsPerInch>
    </o:OfficeDocumentSettings>
    </xml>
    </noscript>
    <![endif]-->
    <!--[if lte mso 11]>
    <style type="text/css">
      .mj-outlook-group-fix { width:100% !important; }
    </style>
    <![endif]-->
    
    
    <style type="text/css">
      @media only screen and (min-width:480px) {
        .mj-column-per-100 { width:100% !important; max-width: 100%; }
      }
    </style>
    <style media="screen and (min-width:480px)">
      .moz-text-html .mj-column-per-100 { width:100% !important; max-width: 100%; }
    </style>
    
    
  
    
    <style type="text/css">

    @media only screen and (max-width:479px) {
      table.mj-full-width-mobile { width: 100% !important; }
      td.mj-full-width-mobile { width: auto !important; }
    }
  
    </style>
    
    
  </head>
  
      <body  style="word-spacing:normal;background-color:#F6F8FC;">
        
    <div style="display:none;font-size:1px;color:#ffffff;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;">{{headline}}</div>
  
        <div
           aria-roledescription="email" role="article" lang="und" dir="auto" style="word-spacing:normal;background-color:#F6F8FC;"
        >
        <!-- Centered gradient banner (locked brand layer). -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#0A1A40" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><v:rect style="width:600px;" xmlns:v="urn:schemas-microsoft-com:vml" fill="true" stroke="false"><v:fill origin="0.5, 0.5" position="0.5, 0.5" src="{{banner_image}}" color="#0A1A40" type="tile" size="1,1" aspect="atleast" /><v:textbox style="mso-fit-shape-to-text:true" inset="0,0,0,0"><![endif]-->
          
      <div  style="background:#0A1A40 url(''{{banner_image}}'') center center / cover repeat;background-position:center center;background-repeat:repeat;background-size:cover;margin:0px auto;max-width:600px;">
        <div  style="line-height:0;font-size:0;">
        <table
           align="center" background="{{banner_image}}" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#0A1A40 url(''{{banner_image}}'') center center / cover repeat;background-position:center center;background-repeat:repeat;background-size:cover;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:48px 24px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="center" style="font-size:0px;padding:0 0 18px 0;word-break:break-word;"
                >
                  
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;"
      >
        <tbody>
          <tr>
            <td  style="width:140px;">
              
      <img
         alt="" src="https://icapos.com/email-logo.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;" width="140" height="auto"
      />
    
            </td>
          </tr>
        </tbody>
      </table>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:28px;font-weight:bold;line-height:1.2;text-align:center;color:#FFFFFF;"
      >{{headline}}</div>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="center" style="font-size:0px;padding:10px 25px;padding-top:8px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:16px;line-height:1.5;text-align:center;color:#C9D8F5;"
      >{{subhead}}</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        </div>
      </div>
    
        <!--[if mso | IE]></v:textbox></v:rect></td></tr></table><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#FFFFFF" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#FFFFFF;background-color:#FFFFFF;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#FFFFFF;background-color:#FFFFFF;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:32px 24px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:separate;line-height:100%;"
      >
        <tbody>
          <tr>
            <td
               align="center" bgcolor="#1A6CE4" role="presentation" style="border:none;border-radius:10px;cursor:auto;mso-padding-alt:16px 32px;background:#1A6CE4;" valign="middle"
            >
              <a
                 href="{{cta_url}}" style="display:inline-block;background:#1A6CE4;color:#FFFFFF;font-family:Helvetica, Arial, sans-serif;font-size:17px;font-weight:bold;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:16px 32px;mso-padding-alt:0px;border-radius:10px;" target="_blank"
              >
                {{cta_text}}
              </a>
            </td>
          </tr>
        </tbody>
      </table>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#F6F8FC" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#F6F8FC;background-color:#F6F8FC;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#F6F8FC;background-color:#F6F8FC;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:8px 24px 24px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:12px;line-height:1.6;text-align:center;color:#5A6B8C;"
      >iCFO Capital Global, Inc. · La Jolla, CA 92037<br />
          <a href="{{unsubscribe_url}}" style="color:#5A6B8C;">Unsubscribe</a> ·
          <a href="{{view_in_browser_url}}" style="color:#5A6B8C;">View in browser</a><br />
          You''re receiving this because you opted in with iCFO Capital Global, Inc.</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    
      </div>
      </body>
    
</html>
  ', '{"slots":[{"key":"headline","type":"text","label":"Headline","max_length":70,"required":true},{"key":"subhead","type":"text","label":"Subhead","max_length":120,"required":false},{"key":"cta_text","type":"text","label":"CTA text","max_length":30,"required":true},{"key":"cta_url","type":"url","label":"CTA link","required":true},{"key":"banner_image","type":"image","label":"Banner image","editable":true,"required":false}],"locked":["logo","brand_colors","footer_legal","unsubscribe"]}'::jsonb)
on conflict (name) do update set
  description = excluded.description,
  mjml_source = excluded.mjml_source,
  compiled_html = excluded.compiled_html,
  placeholder_schema = excluded.placeholder_schema,
  updated_at = now();
