-- Support care: promised reply times, staff reminders, the founder's
-- "did this solve it?" loop, AI triage, and one activity log for every
-- request. Additive + idempotent. Nothing existing is renamed or dropped.

-- ── support_requests: new tracking columns ─────────────────────────────────
alter table public.support_requests
  add column if not exists ref_no               bigint generated by default as identity (start with 1001),
  add column if not exists due_at               timestamptz,      -- promised first reply time
  add column if not exists first_staff_reply_at timestamptz,
  add column if not exists due_soon_alerted_at  timestamptz,      -- "reply due in 2 hours" sent to staff
  add column if not exists overdue_alerted_at   timestamptz,      -- last missed promise handled
  add column if not exists last_reminder_at     timestamptz,      -- last repeat reminder to staff
  add column if not exists reminder_count       integer not null default 0,
  add column if not exists founder_nudged_at    timestamptz,      -- "waiting on you" nudge
  add column if not exists resolution_summary   text,
  add column if not exists confirm_reminded_at  timestamptz,      -- day 2 "did this solve it?" reminder
  add column if not exists closed_at            timestamptz,      -- day 7 auto close, or confirmed
  add column if not exists rating               smallint check (rating between 1 and 5),
  add column if not exists rating_comment       text,
  add column if not exists reopened_count       integer not null default 0,
  add column if not exists ai_triage            jsonb;

create index if not exists support_requests_due_idx
  on public.support_requests (due_at) where first_staff_reply_at is null;

-- ── support_events: the activity log (founder, AI, staff, system, alert) ───
create table if not exists public.support_events (
  id            uuid primary key default gen_random_uuid(),
  request_id    uuid references public.support_requests(id) on delete cascade,
  founder_id    uuid references public.profiles(id) on delete set null,
  actor         text not null check (actor in ('founder', 'ai', 'staff', 'system', 'alert')),
  actor_user_id uuid references public.profiles(id) on delete set null,
  kind          text not null,
  summary       text not null,
  detail        text,
  meta          jsonb,
  created_at    timestamptz not null default now()
);

create index if not exists support_events_request_idx on public.support_events (request_id, created_at);
create index if not exists support_events_kind_idx on public.support_events (kind, created_at desc);
create index if not exists support_events_created_idx on public.support_events (created_at desc);

alter table public.support_events enable row level security;

-- Staff read the log. Writes go through the service role only.
drop policy if exists support_events_staff_read on public.support_events;
create policy support_events_staff_read on public.support_events
  for select using (public.is_staff());

-- ── Backfill: give existing requests their first log entries ───────────────
insert into public.support_events (request_id, founder_id, actor, actor_user_id, kind, summary, detail, created_at)
select r.id, r.founder_id, 'founder', r.founder_id, 'submitted',
       'Founder submitted the request',
       (select m.body from public.support_messages m
         where m.request_id = r.id and m.author_role = 'founder'
         order by m.created_at limit 1),
       r.created_at
from public.support_requests r
where not exists (select 1 from public.support_events e where e.request_id = r.id and e.kind = 'submitted');

insert into public.support_events (request_id, founder_id, actor, kind, summary, meta, created_at)
select r.id, r.founder_id, 'system', 'assigned',
       'Auto assigned to ' || coalesce(p.full_name, p.email, 'staff'),
       jsonb_build_object('assignee', r.assigned_to),
       r.created_at
from public.support_requests r
join public.profiles p on p.id = r.assigned_to
where r.assigned_to is not null
  and not exists (select 1 from public.support_events e where e.request_id = r.id and e.kind = 'assigned');

insert into public.support_events (request_id, founder_id, actor, actor_user_id, kind, summary, created_at)
select m.request_id, r.founder_id,
       case when m.author_role = 'staff' then 'staff' else 'founder' end,
       m.author_user_id,
       case when m.author_role = 'staff' then 'staff_reply' else 'founder_reply' end,
       case when m.author_role = 'staff' then 'Staff replied' else 'Founder replied' end,
       m.created_at
from public.support_messages m
join public.support_requests r on r.id = m.request_id
where m.created_at > (select min(m2.created_at) from public.support_messages m2 where m2.request_id = m.request_id)
  and not exists (select 1 from public.support_events e where e.request_id = m.request_id and e.created_at = m.created_at);

-- Requests from before this migration start quiet: past resolved requests
-- are treated as closed (their founders never got the new "did this solve
-- it?" email), and open ones get their first reminder one interval from now
-- instead of all at once on the first scheduled pass.
update public.support_requests
set closed_at = coalesce(resolved_at, now())
where status = 'resolved' and closed_at is null;

update public.support_requests
set last_reminder_at = coalesce(last_reminder_at, now()),
    founder_nudged_at = case when status = 'pending_founder' then coalesce(founder_nudged_at, now()) else founder_nudged_at end
where status in ('open', 'pending_founder');

-- First staff reply time for requests already answered.
update public.support_requests r
set first_staff_reply_at = sub.first_at
from (
  select request_id, min(created_at) as first_at
  from public.support_messages where author_role = 'staff' group by request_id
) sub
where sub.request_id = r.id and r.first_staff_reply_at is null;
