-- Announcement, Newsletter and Promo: banner, logo, accent color and alignment become
-- design settings, and the footer carries the iCFO disclaimer. Generated by
-- scripts/build-emails.mjs (run with only these three in the manifest). Idempotent via on conflict (name).

insert into public.email_template_masters (name, description, mjml_source, compiled_html, placeholder_schema)
values
  ('Announcement', 'Gradient banner, single column, one call to action.', '<mjml>
  <mj-head>
    <mj-attributes>
      <mj-all font-family="Helvetica, Arial, sans-serif" />
      <mj-text color="#16223F" font-size="15px" line-height="1.6" />
    </mj-attributes>
    <mj-preview>{{headline}}</mj-preview>
  </mj-head>
  <mj-body background-color="#F6F8FC">
    <!-- Banner (design settings): optional full-width banner image on top, then a
         band in the banner color with the chosen logo and the headline, left or center. -->
    <mj-section background-color="#FFFFFF" padding="0">
      <mj-column>
        <mj-text padding="0" font-size="0px" line-height="0px"><!--if:banner_image--><img src="{{banner_image}}" alt="" width="600" style="display:block;width:100%;max-width:600px;height:auto;border:0;" /><!--endif:banner_image--></mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-color="{{banner_bg}}" border-bottom="{{banner_border}}" padding="40px 24px">
      <mj-column>
        <mj-image src="{{logo_url}}" width="132px" align="{{banner_align}}" padding="0 0 16px 0" />
        <mj-text align="{{banner_align}}" color="{{banner_text}}" font-size="26px" font-weight="bold" line-height="1.25" padding="0">{{headline}}</mj-text>
      </mj-column>
    </mj-section>

    <mj-section background-color="#FFFFFF" padding="28px 24px 8px">
      <mj-column>
        <mj-text>{{body}}</mj-text>
      </mj-column>
    </mj-section>

    <mj-section background-color="#FFFFFF" padding="8px 24px 32px">
      <mj-column>
        <mj-button href="{{cta_url}}" background-color="{{accent_color}}" color="#FFFFFF" font-weight="bold" font-size="15px" border-radius="8px"  align="{{banner_align}}" padding="0 25px">{{cta_text}}</mj-button>
      </mj-column>
    </mj-section>

    <!-- Mandatory footer and disclaimer (locked). -->
    <mj-section background-color="#F6F8FC" padding="8px 24px 24px">
      <mj-column>
        <mj-text align="center" color="#5A6B8C" font-size="11px" line-height="1.6">
          iCFO Capital Global, Inc. · 4225 Executive Sq Ste 600, La Jolla, CA 92037<br />
          iCFO Capital Global, Inc. does not solicit securities and is not an investment adviser, broker-dealer, or funding portal. This content is for educational purposes only. It is not an offer to sell or a solicitation of an offer to buy any security, and no assurance of funding is offered or implied.<br />
          <!--if:unsubscribe_url--><a href="{{unsubscribe_url}}" style="color:#5A6B8C;">Unsubscribe</a> ·
          <a href="{{view_in_browser_url}}" style="color:#5A6B8C;">View in browser</a><br /><!--endif:unsubscribe_url-->
          You''re receiving this because you opted in with iCFO Capital Global, Inc.
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
', '<!doctype html>
<html lang="und" dir="auto" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
  <head>
    <title></title>
    <!--[if !mso]><!-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--<![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
      #outlook a { padding:0; }
      body { margin:0;padding:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%; }
      table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt; }
      img { border:0;height:auto;line-height:100%; outline:none;text-decoration:none;-ms-interpolation-mode:bicubic; }
      p { display:block;margin:13px 0; }
    </style>
    <!--[if mso]>
    <noscript>
    <xml>
    <o:OfficeDocumentSettings>
      <o:AllowPNG/>
      <o:PixelsPerInch>96</o:PixelsPerInch>
    </o:OfficeDocumentSettings>
    </xml>
    </noscript>
    <![endif]-->
    <!--[if lte mso 11]>
    <style type="text/css">
      .mj-outlook-group-fix { width:100% !important; }
    </style>
    <![endif]-->
    
    
    <style type="text/css">
      @media only screen and (min-width:480px) {
        .mj-column-per-100 { width:100% !important; max-width: 100%; }
      }
    </style>
    <style media="screen and (min-width:480px)">
      .moz-text-html .mj-column-per-100 { width:100% !important; max-width: 100%; }
    </style>
    
    
  
    
    <style type="text/css">

    @media only screen and (max-width:479px) {
      table.mj-full-width-mobile { width: 100% !important; }
      td.mj-full-width-mobile { width: auto !important; }
    }
  
    </style>
    
    
  </head>
  
      <body  style="word-spacing:normal;background-color:#F6F8FC;">
        
    <div style="display:none;font-size:1px;color:#ffffff;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;">{{headline}}</div>
  
        <div
           aria-roledescription="email" role="article" lang="und" dir="auto" style="word-spacing:normal;background-color:#F6F8FC;"
        >
        <!-- Banner (design settings): optional full-width banner image on top, then a
         band in the banner color with the chosen logo and the headline, left or center. -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#FFFFFF" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#FFFFFF;background-color:#FFFFFF;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#FFFFFF;background-color:#FFFFFF;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:0;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:600px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:0px;line-height:0px;text-align:left;color:#16223F;"
      ><!--if:banner_image--><img src="{{banner_image}}" alt="" width="600" style="display:block;width:100%;max-width:600px;height:auto;border:0;" /><!--endif:banner_image--></div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="{{banner_bg}}" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:{{banner_bg}};background-color:{{banner_bg}};margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:{{banner_bg}};background-color:{{banner_bg}};width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="border-bottom:{{banner_border}};direction:ltr;font-size:0px;padding:40px 24px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="{{banner_align}}" style="font-size:0px;padding:0 0 16px 0;word-break:break-word;"
                >
                  
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;"
      >
        <tbody>
          <tr>
            <td  style="width:132px;">
              
      <img
         alt="" src="{{logo_url}}" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;" width="132" height="auto"
      />
    
            </td>
          </tr>
        </tbody>
      </table>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="{{banner_align}}" style="font-size:0px;padding:0;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:26px;font-weight:bold;line-height:1.25;text-align:{{banner_align}};color:{{banner_text}};"
      >{{headline}}</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#FFFFFF" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#FFFFFF;background-color:#FFFFFF;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#FFFFFF;background-color:#FFFFFF;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:28px 24px 8px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:15px;line-height:1.6;text-align:left;color:#16223F;"
      >{{body}}</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#FFFFFF" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#FFFFFF;background-color:#FFFFFF;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#FFFFFF;background-color:#FFFFFF;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:8px 24px 32px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="{{banner_align}}" style="font-size:0px;padding:0 25px;word-break:break-word;"
                >
                  
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:separate;line-height:100%;"
      >
        <tbody>
          <tr>
            <td
               align="center" bgcolor="{{accent_color}}" role="presentation" style="border:none;border-radius:8px;cursor:auto;mso-padding-alt:10px 25px;background:{{accent_color}};" valign="middle"
            >
              <a
                 href="{{cta_url}}" style="display:inline-block;background:{{accent_color}};color:#FFFFFF;font-family:Helvetica, Arial, sans-serif;font-size:15px;font-weight:bold;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;border-radius:8px;" target="_blank"
              >
                {{cta_text}}
              </a>
            </td>
          </tr>
        </tbody>
      </table>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    <!-- Mandatory footer and disclaimer (locked). -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#F6F8FC" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#F6F8FC;background-color:#F6F8FC;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#F6F8FC;background-color:#F6F8FC;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:8px 24px 24px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:11px;line-height:1.6;text-align:center;color:#5A6B8C;"
      >iCFO Capital Global, Inc. · 4225 Executive Sq Ste 600, La Jolla, CA 92037<br />
          iCFO Capital Global, Inc. does not solicit securities and is not an investment adviser, broker-dealer, or funding portal. This content is for educational purposes only. It is not an offer to sell or a solicitation of an offer to buy any security, and no assurance of funding is offered or implied.<br />
          <!--if:unsubscribe_url--><a href="{{unsubscribe_url}}" style="color:#5A6B8C;">Unsubscribe</a> ·
          <a href="{{view_in_browser_url}}" style="color:#5A6B8C;">View in browser</a><br /><!--endif:unsubscribe_url-->
          You''re receiving this because you opted in with iCFO Capital Global, Inc.</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    
      </div>
      </body>
    
</html>
  ', '{"slots":[{"key":"headline","type":"text","label":"Headline","max_length":90,"required":true},{"key":"body","type":"textarea","label":"Body copy","required":true},{"key":"cta_text","type":"text","label":"CTA text","max_length":30,"required":true},{"key":"cta_url","type":"url","label":"CTA link","required":true},{"key":"banner_image","type":"image","label":"Banner image (1200 x 360)","editable":true,"required":false}],"locked":["logo","brand_colors","footer_legal","unsubscribe","logo_url","accent_color","banner_bg","banner_text","banner_align","banner_border"]}'::jsonb),
  ('Newsletter', 'Image banner with two-column content sections.', '<mjml>
  <mj-head>
    <mj-attributes>
      <mj-all font-family="Helvetica, Arial, sans-serif" />
      <mj-text color="#16223F" font-size="15px" line-height="1.6" />
    </mj-attributes>
    <mj-preview>{{headline}}</mj-preview>
  </mj-head>
  <mj-body background-color="#F6F8FC">
    <!-- Banner (design settings): optional full-width banner image on top, then a
         band in the banner color with the chosen logo and the headline, left or center. -->
    <mj-section background-color="#FFFFFF" padding="0">
      <mj-column>
        <mj-text padding="0" font-size="0px" line-height="0px"><!--if:banner_image--><img src="{{banner_image}}" alt="" width="600" style="display:block;width:100%;max-width:600px;height:auto;border:0;" /><!--endif:banner_image--></mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-color="{{banner_bg}}" border-bottom="{{banner_border}}" padding="44px 24px">
      <mj-column>
        <mj-image src="{{logo_url}}" width="132px" align="{{banner_align}}" padding="0 0 16px 0" />
        <mj-text align="{{banner_align}}" color="{{banner_text}}" font-size="24px" font-weight="bold" line-height="1.25" padding="0">{{headline}}</mj-text>
      </mj-column>
    </mj-section>

    <mj-section background-color="#FFFFFF" padding="26px 24px 6px">
      <mj-column>
        <mj-text>{{intro}}</mj-text>
      </mj-column>
    </mj-section>

    <!-- Two-column section. -->
    <mj-section background-color="#FFFFFF" padding="8px 24px">
      <mj-column>
        <mj-text font-size="17px" font-weight="bold" color="{{accent_color}}">{{section_one_title}}</mj-text>
        <mj-text>{{section_one_body}}</mj-text>
      </mj-column>
      <mj-column>
        <mj-text font-size="17px" font-weight="bold" color="{{accent_color}}">{{section_two_title}}</mj-text>
        <mj-text>{{section_two_body}}</mj-text>
      </mj-column>
    </mj-section>

    <mj-section background-color="#FFFFFF" padding="14px 24px 32px">
      <mj-column>
        <mj-button href="{{cta_url}}" background-color="{{accent_color}}" color="#FFFFFF" font-weight="bold" font-size="15px" border-radius="8px"  align="{{banner_align}}" padding="0 25px">{{cta_text}}</mj-button>
      </mj-column>
    </mj-section>

    <!-- Mandatory footer and disclaimer (locked). -->
    <mj-section background-color="#F6F8FC" padding="8px 24px 24px">
      <mj-column>
        <mj-text align="center" color="#5A6B8C" font-size="11px" line-height="1.6">
          iCFO Capital Global, Inc. · 4225 Executive Sq Ste 600, La Jolla, CA 92037<br />
          iCFO Capital Global, Inc. does not solicit securities and is not an investment adviser, broker-dealer, or funding portal. This content is for educational purposes only. It is not an offer to sell or a solicitation of an offer to buy any security, and no assurance of funding is offered or implied.<br />
          <!--if:unsubscribe_url--><a href="{{unsubscribe_url}}" style="color:#5A6B8C;">Unsubscribe</a> ·
          <a href="{{view_in_browser_url}}" style="color:#5A6B8C;">View in browser</a><br /><!--endif:unsubscribe_url-->
          You''re receiving this because you opted in with iCFO Capital Global, Inc.
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
', '<!doctype html>
<html lang="und" dir="auto" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
  <head>
    <title></title>
    <!--[if !mso]><!-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--<![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
      #outlook a { padding:0; }
      body { margin:0;padding:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%; }
      table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt; }
      img { border:0;height:auto;line-height:100%; outline:none;text-decoration:none;-ms-interpolation-mode:bicubic; }
      p { display:block;margin:13px 0; }
    </style>
    <!--[if mso]>
    <noscript>
    <xml>
    <o:OfficeDocumentSettings>
      <o:AllowPNG/>
      <o:PixelsPerInch>96</o:PixelsPerInch>
    </o:OfficeDocumentSettings>
    </xml>
    </noscript>
    <![endif]-->
    <!--[if lte mso 11]>
    <style type="text/css">
      .mj-outlook-group-fix { width:100% !important; }
    </style>
    <![endif]-->
    
    
    <style type="text/css">
      @media only screen and (min-width:480px) {
        .mj-column-per-100 { width:100% !important; max-width: 100%; }
.mj-column-per-50 { width:50% !important; max-width: 50%; }
      }
    </style>
    <style media="screen and (min-width:480px)">
      .moz-text-html .mj-column-per-100 { width:100% !important; max-width: 100%; }
.moz-text-html .mj-column-per-50 { width:50% !important; max-width: 50%; }
    </style>
    
    
  
    
    <style type="text/css">

    @media only screen and (max-width:479px) {
      table.mj-full-width-mobile { width: 100% !important; }
      td.mj-full-width-mobile { width: auto !important; }
    }
  
    </style>
    
    
  </head>
  
      <body  style="word-spacing:normal;background-color:#F6F8FC;">
        
    <div style="display:none;font-size:1px;color:#ffffff;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;">{{headline}}</div>
  
        <div
           aria-roledescription="email" role="article" lang="und" dir="auto" style="word-spacing:normal;background-color:#F6F8FC;"
        >
        <!-- Banner (design settings): optional full-width banner image on top, then a
         band in the banner color with the chosen logo and the headline, left or center. -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#FFFFFF" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#FFFFFF;background-color:#FFFFFF;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#FFFFFF;background-color:#FFFFFF;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:0;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:600px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:0px;line-height:0px;text-align:left;color:#16223F;"
      ><!--if:banner_image--><img src="{{banner_image}}" alt="" width="600" style="display:block;width:100%;max-width:600px;height:auto;border:0;" /><!--endif:banner_image--></div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="{{banner_bg}}" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:{{banner_bg}};background-color:{{banner_bg}};margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:{{banner_bg}};background-color:{{banner_bg}};width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="border-bottom:{{banner_border}};direction:ltr;font-size:0px;padding:44px 24px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="{{banner_align}}" style="font-size:0px;padding:0 0 16px 0;word-break:break-word;"
                >
                  
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;"
      >
        <tbody>
          <tr>
            <td  style="width:132px;">
              
      <img
         alt="" src="{{logo_url}}" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;" width="132" height="auto"
      />
    
            </td>
          </tr>
        </tbody>
      </table>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="{{banner_align}}" style="font-size:0px;padding:0;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:24px;font-weight:bold;line-height:1.25;text-align:{{banner_align}};color:{{banner_text}};"
      >{{headline}}</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#FFFFFF" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#FFFFFF;background-color:#FFFFFF;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#FFFFFF;background-color:#FFFFFF;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:26px 24px 6px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:15px;line-height:1.6;text-align:left;color:#16223F;"
      >{{intro}}</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    <!-- Two-column section. -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#FFFFFF" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#FFFFFF;background-color:#FFFFFF;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#FFFFFF;background-color:#FFFFFF;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:8px 24px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:276px;" ><![endif]-->
            
      <div
         class="mj-column-per-50 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:17px;font-weight:bold;line-height:1.6;text-align:left;color:{{accent_color}};"
      >{{section_one_title}}</div>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:15px;line-height:1.6;text-align:left;color:#16223F;"
      >{{section_one_body}}</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td><td class="" style="vertical-align:top;width:276px;" ><![endif]-->
            
      <div
         class="mj-column-per-50 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:17px;font-weight:bold;line-height:1.6;text-align:left;color:{{accent_color}};"
      >{{section_two_title}}</div>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:15px;line-height:1.6;text-align:left;color:#16223F;"
      >{{section_two_body}}</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#FFFFFF" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#FFFFFF;background-color:#FFFFFF;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#FFFFFF;background-color:#FFFFFF;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:14px 24px 32px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="{{banner_align}}" style="font-size:0px;padding:0 25px;word-break:break-word;"
                >
                  
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:separate;line-height:100%;"
      >
        <tbody>
          <tr>
            <td
               align="center" bgcolor="{{accent_color}}" role="presentation" style="border:none;border-radius:8px;cursor:auto;mso-padding-alt:10px 25px;background:{{accent_color}};" valign="middle"
            >
              <a
                 href="{{cta_url}}" style="display:inline-block;background:{{accent_color}};color:#FFFFFF;font-family:Helvetica, Arial, sans-serif;font-size:15px;font-weight:bold;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;border-radius:8px;" target="_blank"
              >
                {{cta_text}}
              </a>
            </td>
          </tr>
        </tbody>
      </table>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    <!-- Mandatory footer and disclaimer (locked). -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#F6F8FC" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#F6F8FC;background-color:#F6F8FC;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#F6F8FC;background-color:#F6F8FC;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:8px 24px 24px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:11px;line-height:1.6;text-align:center;color:#5A6B8C;"
      >iCFO Capital Global, Inc. · 4225 Executive Sq Ste 600, La Jolla, CA 92037<br />
          iCFO Capital Global, Inc. does not solicit securities and is not an investment adviser, broker-dealer, or funding portal. This content is for educational purposes only. It is not an offer to sell or a solicitation of an offer to buy any security, and no assurance of funding is offered or implied.<br />
          <!--if:unsubscribe_url--><a href="{{unsubscribe_url}}" style="color:#5A6B8C;">Unsubscribe</a> ·
          <a href="{{view_in_browser_url}}" style="color:#5A6B8C;">View in browser</a><br /><!--endif:unsubscribe_url-->
          You''re receiving this because you opted in with iCFO Capital Global, Inc.</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    
      </div>
      </body>
    
</html>
  ', '{"slots":[{"key":"headline","type":"text","label":"Headline","max_length":90,"required":true},{"key":"intro","type":"richtext","label":"Intro paragraph","required":true},{"key":"section_one_title","type":"text","label":"Section 1 title","max_length":60,"required":true},{"key":"section_one_body","type":"richtext","label":"Section 1 body","required":true},{"key":"section_two_title","type":"text","label":"Section 2 title","max_length":60,"required":true},{"key":"section_two_body","type":"richtext","label":"Section 2 body","required":true},{"key":"cta_text","type":"text","label":"CTA text","max_length":30,"required":true},{"key":"cta_url","type":"url","label":"CTA link","required":true},{"key":"banner_image","type":"image","label":"Banner image (1200 x 360)","editable":true,"required":false}],"locked":["logo","brand_colors","footer_legal","unsubscribe","logo_url","accent_color","banner_bg","banner_text","banner_align","banner_border"]}'::jsonb),
  ('Promo', 'Centered gradient banner, short copy, large call to action.', '<mjml>
  <mj-head>
    <mj-attributes>
      <mj-all font-family="Helvetica, Arial, sans-serif" />
      <mj-text color="#16223F" font-size="15px" line-height="1.6" />
    </mj-attributes>
    <mj-preview>{{headline}}</mj-preview>
  </mj-head>
  <mj-body background-color="#F6F8FC">
    <!-- Banner (design settings): optional full-width banner image on top, then a
         band in the banner color with the chosen logo and the headline, left or center. -->
    <mj-section background-color="#FFFFFF" padding="0">
      <mj-column>
        <mj-text padding="0" font-size="0px" line-height="0px"><!--if:banner_image--><img src="{{banner_image}}" alt="" width="600" style="display:block;width:100%;max-width:600px;height:auto;border:0;" /><!--endif:banner_image--></mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-color="{{banner_bg}}" border-bottom="{{banner_border}}" padding="48px 24px">
      <mj-column>
        <mj-image src="{{logo_url}}" width="140px" align="{{banner_align}}" padding="0 0 16px 0" />
        <mj-text align="{{banner_align}}" color="{{banner_text}}" font-size="28px" font-weight="bold" line-height="1.2" padding="0">{{headline}}</mj-text>
        <mj-text align="{{banner_align}}" color="{{banner_text}}" font-size="16px" line-height="1.5" padding="8px 0 0 0">{{subhead}}</mj-text>
      </mj-column>
    </mj-section>

    <mj-section background-color="#FFFFFF" padding="32px 24px">
      <mj-column>
        <mj-button href="{{cta_url}}" background-color="{{accent_color}}" color="#FFFFFF" font-weight="bold" font-size="17px" border-radius="8px" inner-padding="16px 32px" align="{{banner_align}}" padding="0 25px">{{cta_text}}</mj-button>
      </mj-column>
    </mj-section>

    <!-- Mandatory footer and disclaimer (locked). -->
    <mj-section background-color="#F6F8FC" padding="8px 24px 24px">
      <mj-column>
        <mj-text align="center" color="#5A6B8C" font-size="11px" line-height="1.6">
          iCFO Capital Global, Inc. · 4225 Executive Sq Ste 600, La Jolla, CA 92037<br />
          iCFO Capital Global, Inc. does not solicit securities and is not an investment adviser, broker-dealer, or funding portal. This content is for educational purposes only. It is not an offer to sell or a solicitation of an offer to buy any security, and no assurance of funding is offered or implied.<br />
          <!--if:unsubscribe_url--><a href="{{unsubscribe_url}}" style="color:#5A6B8C;">Unsubscribe</a> ·
          <a href="{{view_in_browser_url}}" style="color:#5A6B8C;">View in browser</a><br /><!--endif:unsubscribe_url-->
          You''re receiving this because you opted in with iCFO Capital Global, Inc.
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
', '<!doctype html>
<html lang="und" dir="auto" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
  <head>
    <title></title>
    <!--[if !mso]><!-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--<![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
      #outlook a { padding:0; }
      body { margin:0;padding:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%; }
      table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt; }
      img { border:0;height:auto;line-height:100%; outline:none;text-decoration:none;-ms-interpolation-mode:bicubic; }
      p { display:block;margin:13px 0; }
    </style>
    <!--[if mso]>
    <noscript>
    <xml>
    <o:OfficeDocumentSettings>
      <o:AllowPNG/>
      <o:PixelsPerInch>96</o:PixelsPerInch>
    </o:OfficeDocumentSettings>
    </xml>
    </noscript>
    <![endif]-->
    <!--[if lte mso 11]>
    <style type="text/css">
      .mj-outlook-group-fix { width:100% !important; }
    </style>
    <![endif]-->
    
    
    <style type="text/css">
      @media only screen and (min-width:480px) {
        .mj-column-per-100 { width:100% !important; max-width: 100%; }
      }
    </style>
    <style media="screen and (min-width:480px)">
      .moz-text-html .mj-column-per-100 { width:100% !important; max-width: 100%; }
    </style>
    
    
  
    
    <style type="text/css">

    @media only screen and (max-width:479px) {
      table.mj-full-width-mobile { width: 100% !important; }
      td.mj-full-width-mobile { width: auto !important; }
    }
  
    </style>
    
    
  </head>
  
      <body  style="word-spacing:normal;background-color:#F6F8FC;">
        
    <div style="display:none;font-size:1px;color:#ffffff;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;">{{headline}}</div>
  
        <div
           aria-roledescription="email" role="article" lang="und" dir="auto" style="word-spacing:normal;background-color:#F6F8FC;"
        >
        <!-- Banner (design settings): optional full-width banner image on top, then a
         band in the banner color with the chosen logo and the headline, left or center. -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#FFFFFF" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#FFFFFF;background-color:#FFFFFF;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#FFFFFF;background-color:#FFFFFF;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:0;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:600px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:0px;line-height:0px;text-align:left;color:#16223F;"
      ><!--if:banner_image--><img src="{{banner_image}}" alt="" width="600" style="display:block;width:100%;max-width:600px;height:auto;border:0;" /><!--endif:banner_image--></div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="{{banner_bg}}" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:{{banner_bg}};background-color:{{banner_bg}};margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:{{banner_bg}};background-color:{{banner_bg}};width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="border-bottom:{{banner_border}};direction:ltr;font-size:0px;padding:48px 24px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="{{banner_align}}" style="font-size:0px;padding:0 0 16px 0;word-break:break-word;"
                >
                  
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;"
      >
        <tbody>
          <tr>
            <td  style="width:140px;">
              
      <img
         alt="" src="{{logo_url}}" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;" width="140" height="auto"
      />
    
            </td>
          </tr>
        </tbody>
      </table>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="{{banner_align}}" style="font-size:0px;padding:0;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:28px;font-weight:bold;line-height:1.2;text-align:{{banner_align}};color:{{banner_text}};"
      >{{headline}}</div>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="{{banner_align}}" style="font-size:0px;padding:8px 0 0 0;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:16px;line-height:1.5;text-align:{{banner_align}};color:{{banner_text}};"
      >{{subhead}}</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#FFFFFF" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#FFFFFF;background-color:#FFFFFF;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#FFFFFF;background-color:#FFFFFF;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:32px 24px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="{{banner_align}}" style="font-size:0px;padding:0 25px;word-break:break-word;"
                >
                  
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:separate;line-height:100%;"
      >
        <tbody>
          <tr>
            <td
               align="center" bgcolor="{{accent_color}}" role="presentation" style="border:none;border-radius:8px;cursor:auto;mso-padding-alt:16px 32px;background:{{accent_color}};" valign="middle"
            >
              <a
                 href="{{cta_url}}" style="display:inline-block;background:{{accent_color}};color:#FFFFFF;font-family:Helvetica, Arial, sans-serif;font-size:17px;font-weight:bold;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:16px 32px;mso-padding-alt:0px;border-radius:8px;" target="_blank"
              >
                {{cta_text}}
              </a>
            </td>
          </tr>
        </tbody>
      </table>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    <!-- Mandatory footer and disclaimer (locked). -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#F6F8FC" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#F6F8FC;background-color:#F6F8FC;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#F6F8FC;background-color:#F6F8FC;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:8px 24px 24px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:552px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Helvetica, Arial, sans-serif;font-size:11px;line-height:1.6;text-align:center;color:#5A6B8C;"
      >iCFO Capital Global, Inc. · 4225 Executive Sq Ste 600, La Jolla, CA 92037<br />
          iCFO Capital Global, Inc. does not solicit securities and is not an investment adviser, broker-dealer, or funding portal. This content is for educational purposes only. It is not an offer to sell or a solicitation of an offer to buy any security, and no assurance of funding is offered or implied.<br />
          <!--if:unsubscribe_url--><a href="{{unsubscribe_url}}" style="color:#5A6B8C;">Unsubscribe</a> ·
          <a href="{{view_in_browser_url}}" style="color:#5A6B8C;">View in browser</a><br /><!--endif:unsubscribe_url-->
          You''re receiving this because you opted in with iCFO Capital Global, Inc.</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    
      </div>
      </body>
    
</html>
  ', '{"slots":[{"key":"headline","type":"text","label":"Headline","max_length":70,"required":true},{"key":"subhead","type":"text","label":"Subhead","max_length":120,"required":false},{"key":"cta_text","type":"text","label":"CTA text","max_length":30,"required":true},{"key":"cta_url","type":"url","label":"CTA link","required":true},{"key":"banner_image","type":"image","label":"Banner image (1200 x 360)","editable":true,"required":false}],"locked":["logo","brand_colors","footer_legal","unsubscribe","logo_url","accent_color","banner_bg","banner_text","banner_align","banner_border"]}'::jsonb)
on conflict (name) do update set
  description = excluded.description,
  mjml_source = excluded.mjml_source,
  compiled_html = excluded.compiled_html,
  placeholder_schema = excluded.placeholder_schema,
  updated_at = now();
